/** Website texts (account), keyed by the German original. */
export const account: Record<string, { fr: string; it: string; en: string }> = {
  // Member pages: general
  Konto: { fr: 'Compte', it: 'Account', en: 'Account' },
  'Mein Konto': { fr: 'Mon compte', it: 'Il mio account', en: 'My account' },
  Anmelden: { fr: 'Se connecter', it: 'Accedi', en: 'Sign in' },
  Abmelden: { fr: 'Se déconnecter', it: 'Esci', en: 'Sign out' },
  'E-Mail': { fr: 'E-mail', it: 'E-mail', en: 'Email' },
  Passwort: { fr: 'Mot de passe', it: 'Password', en: 'Password' },
  Name: { fr: 'Nom', it: 'Nome', en: 'Name' },
  Speichern: { fr: 'Enregistrer', it: 'Salva', en: 'Save' },
  'Gespeichert.': { fr: 'Enregistré.', it: 'Salvato.', en: 'Saved.' },
  'Zur Startseite': { fr: 'Retour à l’accueil', it: 'Alla pagina iniziale', en: 'Go to home page' },
  'Bitte leer lassen': { fr: 'Veuillez laisser vide', it: 'Lascia vuoto', en: 'Please leave empty' },
  'Anfrage von fremder Herkunft abgelehnt.': { fr: 'Requête d’une origine externe refusée.', it: 'Richiesta di origine esterna rifiutata.', en: 'Request from a foreign origin rejected.' },
  'Zu viele Versuche. Bitte warte eine Viertelstunde.': {
    fr: 'Trop de tentatives. Veuillez patienter un quart d’heure.',
    it: 'Troppi tentativi. Aspetta un quarto d’ora.',
    en: 'Too many attempts. Please wait fifteen minutes.',
  },
  'Zu viele Versuche. Bitte versuch es später nochmals.': {
    fr: 'Trop de tentatives. Veuillez réessayer plus tard.',
    it: 'Troppi tentativi. Riprova più tardi.',
    en: 'Too many attempts. Please try again later.',
  },

  // Sign in
  'Passwort vergessen?': { fr: 'Mot de passe oublié?', it: 'Password dimenticata?', en: 'Forgot your password?' },
  'Bestätigungslink nochmals schicken': { fr: 'Renvoyer le lien de confirmation', it: 'Invia di nuovo il link di conferma', en: 'Resend the confirmation link' },
  'Noch kein Konto?': { fr: 'Pas encore de compte?', it: 'Non hai ancora un account?', en: 'No account yet?' },
  'Konto erstellen': { fr: 'Créer un compte', it: 'Crea un account', en: 'Create an account' },
  'Bitte melde dich nochmals an.': { fr: 'Veuillez vous reconnecter.', it: 'Accedi di nuovo.', en: 'Please sign in again.' },
  'E-Mail oder Passwort stimmen nicht.': { fr: 'L’e-mail ou le mot de passe est incorrect.', it: 'E-mail o password errate.', en: 'The email or password is incorrect.' },
  'Dieses Konto ist gesperrt. Melde dich bei uns, wenn das ein Irrtum ist.': {
    fr: 'Ce compte est bloqué. Contactez-nous s’il s’agit d’une erreur.',
    it: 'Questo account è bloccato. Contattaci se si tratta di un errore.',
    en: 'This account is blocked. Get in touch with us if this is a mistake.',
  },
  'Bitte bestätige zuerst deine E-Mail-Adresse. Den Link haben wir dir bei der Registrierung geschickt.': {
    fr: 'Veuillez d’abord confirmer votre adresse e-mail. Nous vous avons envoyé le lien lors de l’inscription.',
    it: 'Conferma prima il tuo indirizzo e-mail. Ti abbiamo inviato il link al momento della registrazione.',
    en: 'Please confirm your email address first. We sent you the link when you signed up.',
  },

  // Sign up
  'Nur auf Einladung': { fr: 'Sur invitation uniquement', it: 'Solo su invito', en: 'By invitation only' },
  'Neue Konten richtet {name} selbst ein. Hast du eine Einladung bekommen? Der Link darin führt direkt zum Passwort.': {
    fr: '{name} crée lui-même les nouveaux comptes. Vous avez reçu une invitation? Le lien qu’elle contient vous mène directement au mot de passe.',
    it: 'I nuovi account li crea {name} direttamente. Hai ricevuto un invito? Il link al suo interno ti porta direttamente alla password.',
    en: '{name} sets up new accounts themselves. Did you get an invitation? The link in it takes you straight to choosing a password.',
  },
  'Neue Konten gibt es nur auf Einladung.': { fr: 'Les nouveaux comptes sont créés uniquement sur invitation.', it: 'I nuovi account sono disponibili solo su invito.', en: 'New accounts are by invitation only.' },
  'Kostenlos. Für alles Weitere gibt es danach die {plan} ({price}).': {
    fr: 'Gratuit. Pour tout le reste, il y a ensuite l’offre {plan} ({price}).',
    it: 'Gratis. Per tutto il resto c’è poi l’offerta {plan} ({price}).',
    en: 'Free. For everything else, there’s the {plan} afterwards ({price}).',
  },
  'Mindestens 10 Zeichen. Ein Satz ist leichter zu merken als Sonderzeichen.': {
    fr: 'Au moins 10 caractères. Une phrase se retient plus facilement que des caractères spéciaux.',
    it: 'Almeno 10 caratteri. Una frase si ricorda più facilmente dei caratteri speciali.',
    en: 'At least 10 characters. A sentence is easier to remember than special characters.',
  },
  'Newsletter abonnieren': { fr: 'S’abonner à la newsletter', it: 'Iscriviti alla newsletter', en: 'Subscribe to the newsletter' },
  'Wir speichern Name und E-Mail für dein Konto. Mehr in der {link}.': {
    fr: 'Nous enregistrons votre nom et votre e-mail pour votre compte. Plus d’informations dans la {link}.',
    it: 'Salviamo nome ed e-mail per il tuo account. Maggiori informazioni nell’{link}.',
    en: 'We store your name and email for your account. More in the {link}.',
  },
  Datenschutzerklärung: { fr: 'déclaration de protection des données', it: 'informativa sulla privacy', en: 'privacy policy' },
  'Schon dabei?': { fr: 'Déjà inscrit?', it: 'Sei già registrato?', en: 'Already have an account?' },
  'Fast geschafft': { fr: 'Presque terminé', it: 'Quasi fatto', en: 'Almost done' },
  'Schau in dein Postfach.': { fr: 'Consultez votre boîte de réception.', it: 'Controlla la tua casella di posta.', en: 'Check your inbox.' },
  'Wir haben dir einen Link geschickt. Ein Klick darauf bestätigt deine E-Mail-Adresse, danach bist du angemeldet.': {
    fr: 'Nous vous avons envoyé un lien. Un clic suffit pour confirmer votre adresse e-mail, ensuite vous êtes connecté.',
    it: 'Ti abbiamo inviato un link. Un clic conferma il tuo indirizzo e-mail, dopodiché hai effettuato l’accesso.',
    en: 'We’ve sent you a link. One click confirms your email address, and then you’re signed in.',
  },
  'Nichts angekommen? Schau im Spam-Ordner nach oder {link} – dort kannst du den Link nochmals anfordern.': {
    fr: 'Rien reçu? Vérifiez votre dossier de spam ou {link} – vous pourrez y demander à nouveau le lien.',
    it: 'Non è arrivato nulla? Controlla la cartella spam oppure {link}: lì puoi richiedere di nuovo il link.',
    en: 'Nothing arrived? Check your spam folder or {link} – you can request the link again there.',
  },
  'melde dich an': { fr: 'connectez-vous', it: 'accedi', en: 'sign in' },
  'Wie heisst du?': { fr: 'Quel est votre nom?', it: 'Come ti chiami?', en: 'What’s your name?' },
  'Bitte gib eine gültige E-Mail-Adresse ein.': { fr: 'Veuillez saisir une adresse e-mail valable.', it: 'Inserisci un indirizzo e-mail valido.', en: 'Please enter a valid email address.' },
  'Das Passwort braucht mindestens 10 Zeichen. Ein Satz ist leichter zu merken als Sonderzeichen.': {
    fr: 'Le mot de passe doit comporter au moins 10 caractères. Une phrase se retient plus facilement que des caractères spéciaux.',
    it: 'La password deve avere almeno 10 caratteri. Una frase si ricorda più facilmente dei caratteri speciali.',
    en: 'The password needs at least 10 characters. A sentence is easier to remember than special characters.',
  },
  'Das Passwort ist zu lang.': { fr: 'Le mot de passe est trop long.', it: 'La password è troppo lunga.', en: 'The password is too long.' },

  // Confirmation link
  'Link abgelaufen': { fr: 'Lien expiré', it: 'Link scaduto', en: 'Link expired' },
  'Dieser Link ist nicht mehr gültig.': { fr: 'Ce lien n’est plus valable.', it: 'Questo link non è più valido.', en: 'This link is no longer valid.' },
  'Vielleicht hast du dein Konto schon bestätigt – dann kannst du dich einfach anmelden. Sonst schicken wir dir gerne einen neuen Link.': {
    fr: 'Vous avez peut-être déjà confirmé votre compte – dans ce cas, connectez-vous simplement. Sinon, nous vous enverrons volontiers un nouveau lien.',
    it: 'Forse hai già confermato il tuo account: in tal caso puoi semplicemente accedere. Altrimenti ti inviamo volentieri un nuovo link.',
    en: 'Maybe you’ve already confirmed your account – then you can simply sign in. Otherwise we’ll gladly send you a new link.',
  },
  'Konto bestätigen': { fr: 'Confirmer le compte', it: 'Conferma l’account', en: 'Confirm account' },
  'Fast geschafft.': { fr: 'Presque terminé.', it: 'Quasi fatto.', en: 'Almost done.' },
  'Ein Klick noch, dann ist deine E-Mail-Adresse bestätigt und du bist angemeldet.': {
    fr: 'Encore un clic, et votre adresse e-mail sera confirmée et vous serez connecté.',
    it: 'Ancora un clic e il tuo indirizzo e-mail sarà confermato e avrai effettuato l’accesso.',
    en: 'One more click and your email address is confirmed and you’re signed in.',
  },

  // Password
  'Passwort vergessen': { fr: 'Mot de passe oublié', it: 'Password dimenticata', en: 'Forgot password' },
  'Wenn es zu dieser Adresse ein Konto gibt, ist der Link unterwegs. Er gilt zwei Stunden.': {
    fr: 'S’il existe un compte pour cette adresse, le lien est en route. Il est valable deux heures.',
    it: 'Se esiste un account per questo indirizzo, il link è in arrivo. È valido due ore.',
    en: 'If there’s an account for this address, the link is on its way. It’s valid for two hours.',
  },
  'Kein Problem. Gib deine E-Mail-Adresse ein, wir schicken dir einen Link für ein neues Passwort.': {
    fr: 'Pas de problème. Saisissez votre adresse e-mail, nous vous enverrons un lien pour choisir un nouveau mot de passe.',
    it: 'Nessun problema. Inserisci il tuo indirizzo e-mail e ti inviamo un link per una nuova password.',
    en: 'No problem. Enter your email address and we’ll send you a link to set a new password.',
  },
  'Link schicken': { fr: 'Envoyer le lien', it: 'Invia il link', en: 'Send link' },
  'Zurück zur Anmeldung': { fr: 'Retour à la connexion', it: 'Torna all’accesso', en: 'Back to sign in' },
  'Neues Passwort': { fr: 'Nouveau mot de passe', it: 'Nuova password', en: 'New password' },
  'Mindestens 10 Zeichen.': { fr: 'Au moins 10 caractères.', it: 'Almeno 10 caratteri.', en: 'At least 10 characters.' },
  'Speichern und anmelden': { fr: 'Enregistrer et se connecter', it: 'Salva e accedi', en: 'Save and sign in' },
  'Dieser Link ist abgelaufen.': { fr: 'Ce lien a expiré.', it: 'Questo link è scaduto.', en: 'This link has expired.' },
  'Aus Sicherheitsgründen gilt er nur kurz. Fordere einfach einen neuen an.': {
    fr: 'Pour des raisons de sécurité, il n’est valable que peu de temps. Demandez-en simplement un nouveau.',
    it: 'Per motivi di sicurezza è valido solo per poco tempo. Richiedine semplicemente uno nuovo.',
    en: 'For security reasons it’s only valid for a short time. Just request a new one.',
  },
  'Neuen Link anfordern': { fr: 'Demander un nouveau lien', it: 'Richiedi un nuovo link', en: 'Request a new link' },
  'Der Link ist abgelaufen. Fordere einfach einen neuen an.': {
    fr: 'Le lien a expiré. Demandez-en simplement un nouveau.',
    it: 'Il link è scaduto. Richiedine semplicemente uno nuovo.',
    en: 'The link has expired. Just request a new one.',
  },

  // Account
  'Willkommen! Deine E-Mail-Adresse ist bestätigt.': { fr: 'Bienvenue! Votre adresse e-mail est confirmée.', it: 'Benvenuto! Il tuo indirizzo e-mail è confermato.', en: 'Welcome! Your email address is confirmed.' },
  'Dein neues Passwort ist gespeichert.': { fr: 'Votre nouveau mot de passe est enregistré.', it: 'La tua nuova password è stata salvata.', en: 'Your new password has been saved.' },
  'Danke! Deine Mitgliedschaft ist aktiv. Die Quittung kommt per E-Mail von Stripe.': {
    fr: 'Merci! Votre adhésion est active. Vous recevrez le reçu par e-mail de Stripe.',
    it: 'Grazie! La tua iscrizione è attiva. La ricevuta ti arriverà via e-mail da Stripe.',
    en: 'Thank you! Your membership is active. Stripe will email you the receipt.',
  },
  '{plan} – gekündigt, läuft bis {date}': { fr: '{plan} – résilié, valable jusqu’au {date}', it: '{plan} – disdetto, valido fino al {date}', en: '{plan} – cancelled, runs until {date}' },
  '{plan} – die letzte Zahlung ist offen': { fr: '{plan} – le dernier paiement est en attente', it: '{plan} – l’ultimo pagamento è in sospeso', en: '{plan} – the last payment is outstanding' },
  '{plan} – verlängert sich am {date}': { fr: '{plan} – se renouvelle le {date}', it: '{plan} – si rinnova il {date}', en: '{plan} – renews on {date}' },
  '{plan} bis {date}': { fr: '{plan} jusqu’au {date}', it: '{plan} fino al {date}', en: '{plan} until {date}' },
  'Kostenloses Konto': { fr: 'Compte gratuit', it: 'Account gratuito', en: 'Free account' },
  'Hallo {name}': { fr: 'Bonjour {name}', it: 'Ciao {name}', en: 'Hello {name}' },
  'Weiter, wo du warst': { fr: 'Reprendre là où vous étiez', it: 'Continua da dove eri rimasto', en: 'Continue where you left off' },
  Mitgliedschaft: { fr: 'Adhésion', it: 'Abbonamento', en: 'Membership' },
  '{plan} abschliessen – {price}': { fr: 'Souscrire {plan} – {price}', it: 'Abbonati a {plan} – {price}', en: 'Get {plan} – {price}' },
  '{price} pro Jahr': { fr: '{price} par an', it: '{price} all’anno', en: '{price} per year' },
  '{price} pro Monat': { fr: '{price} par mois', it: '{price} al mese', en: '{price} per month' },
  'Abo, Karte und Quittungen': { fr: 'Abonnement, carte et reçus', it: 'Abbonamento, carta e ricevute', en: 'Subscription, card and receipts' },
  Angaben: { fr: 'Informations', it: 'Dati', en: 'Details' },
  'Für eine neue Adresse schreib uns kurz.': {
    fr: 'Pour changer d’adresse, écrivez-nous un petit message.',
    it: 'Per un nuovo indirizzo scrivici due righe.',
    en: 'To change your address, just drop us a line.',
  },
  'Passwort ändern': { fr: 'Changer le mot de passe', it: 'Cambia password', en: 'Change password' },
  'Bisheriges Passwort': { fr: 'Mot de passe actuel', it: 'Password attuale', en: 'Current password' },
  'Konto löschen': { fr: 'Supprimer le compte', it: 'Elimina l’account', en: 'Delete account' },
  'Konto wirklich löschen?': { fr: 'Vraiment supprimer le compte?', it: 'Eliminare davvero l’account?', en: 'Really delete your account?' },
  'Dein Abo wird sofort beendet.': { fr: 'Votre abonnement prendra fin immédiatement.', it: 'Il tuo abbonamento terminerà subito.', en: 'Your subscription ends immediately.' },
  'Alles, was zu deinem Konto gehört, wird gelöscht. Das lässt sich nicht rückgängig machen.': {
    fr: 'Tout ce qui est lié à votre compte sera supprimé. Cette action est irréversible.',
    it: 'Tutto ciò che appartiene al tuo account verrà eliminato. L’operazione non può essere annullata.',
    en: 'Everything that belongs to your account will be deleted. This can’t be undone.',
  },
  'Zur Sicherheit: dein Passwort': { fr: 'Par sécurité: votre mot de passe', it: 'Per sicurezza: la tua password', en: 'For security: your password' },
  'Ja, löschen': { fr: 'Oui, supprimer', it: 'Sì, elimina', en: 'Yes, delete' },
  'Nein, behalten': { fr: 'Non, conserver', it: 'No, mantieni', en: 'No, keep it' },
  'Der Name darf nicht leer sein.': { fr: 'Le nom ne peut pas être vide.', it: 'Il nome non può essere vuoto.', en: 'The name can’t be empty.' },
  'Das bisherige Passwort stimmt nicht.': { fr: 'Le mot de passe actuel est incorrect.', it: 'La password attuale non è corretta.', en: 'The current password is incorrect.' },
  'Das Passwort stimmt nicht.': { fr: 'Le mot de passe est incorrect.', it: 'La password non è corretta.', en: 'The password is incorrect.' },
  'Die bezahlte Mitgliedschaft ist gerade nicht verfügbar.': {
    fr: 'L’adhésion payante n’est pas disponible pour le moment.',
    it: 'L’iscrizione a pagamento non è disponibile al momento.',
    en: 'The paid membership isn’t available right now.',
  },
  'Zu diesem Konto gibt es kein Abo.': { fr: 'Ce compte n’a pas d’abonnement.', it: 'Questo account non ha un abbonamento.', en: 'This account has no subscription.' },
  'Konto gelöscht': { fr: 'Compte supprimé', it: 'Account eliminato', en: 'Account deleted' },
  'Dein Konto ist gelöscht.': { fr: 'Votre compte est supprimé.', it: 'Il tuo account è stato eliminato.', en: 'Your account has been deleted.' },
  'Danke, dass du dabei warst. Alles Gute von {name}!': {
    fr: 'Merci d’avoir été des nôtres. Avec les meilleurs vœux de {name}!',
    it: 'Grazie per essere stato con noi. Tanti auguri da {name}!',
    en: 'Thanks for being with us. All the best from {name}!',
  },

  // Member mails
  'Hallo {name},': { fr: 'Bonjour {name},', it: 'Ciao {name},', en: 'Hello {name},' },
  'Hallo,': { fr: 'Bonjour,', it: 'Ciao,', en: 'Hello,' },
  'Dein Konto bei {name}': { fr: 'Votre compte chez {name}', it: 'Il tuo account presso {name}', en: 'Your account at {name}' },
  'jemand wollte mit dieser Adresse ein neues Konto anlegen. Du hast aber schon eines.': {
    fr: 'quelqu’un a voulu créer un nouveau compte avec cette adresse. Mais vous en avez déjà un.',
    it: 'qualcuno ha voluto creare un nuovo account con questo indirizzo. Ma ne hai già uno.',
    en: 'someone tried to create a new account with this address. But you already have one.',
  },
  'Anmelden: {url}': { fr: 'Se connecter: {url}', it: 'Accedi: {url}', en: 'Sign in: {url}' },
  'Passwort vergessen? {url}': { fr: 'Mot de passe oublié? {url}', it: 'Password dimenticata? {url}', en: 'Forgot your password? {url}' },
  'Warst du das nicht? Dann kannst du diese E-Mail ignorieren.': {
    fr: 'Ce n’était pas vous? Vous pouvez alors ignorer cet e-mail.',
    it: 'Non sei stato tu? Allora puoi ignorare questa e-mail.',
    en: 'Wasn’t you? Then you can ignore this email.',
  },
  'Bitte bestätige dein Konto bei {name}': { fr: 'Veuillez confirmer votre compte chez {name}', it: 'Conferma il tuo account presso {name}', en: 'Please confirm your account at {name}' },
  'willkommen! Ein Klick bestätigt deine E-Mail-Adresse, danach bist du angemeldet:': {
    fr: 'bienvenue! Un clic confirme votre adresse e-mail, ensuite vous êtes connecté:',
    it: 'benvenuto! Un clic conferma il tuo indirizzo e-mail, dopodiché hai effettuato l’accesso:',
    en: 'welcome! One click confirms your email address, and then you’re signed in:',
  },
  'Der Link gilt drei Tage. Hast du dich nicht registriert? Dann ignoriere diese E-Mail einfach.': {
    fr: 'Le lien est valable trois jours. Vous ne vous êtes pas inscrit? Ignorez simplement cet e-mail.',
    it: 'Il link è valido tre giorni. Non ti sei registrato? Allora ignora semplicemente questa e-mail.',
    en: 'The link is valid for three days. Didn’t sign up? Then just ignore this email.',
  },
  'hier ist der Link nochmals:': { fr: 'voici à nouveau le lien:', it: 'ecco di nuovo il link:', en: 'here’s the link again:' },
  'Neues Passwort für {name}': { fr: 'Nouveau mot de passe pour {name}', it: 'Nuova password per {name}', en: 'New password for {name}' },
  'mit diesem Link legst du ein neues Passwort fest. Er gilt zwei Stunden:': {
    fr: 'ce lien vous permet de définir un nouveau mot de passe. Il est valable deux heures:',
    it: 'con questo link imposti una nuova password. È valido due ore:',
    en: 'use this link to set a new password. It’s valid for two hours:',
  },
  'Hast du das nicht angefordert? Dann bleibt alles, wie es ist.': {
    fr: 'Vous ne l’avez pas demandé? Alors rien ne change.',
    it: 'Non l’hai richiesto tu? Allora resta tutto com’è.',
    en: 'Didn’t request this? Then everything stays as it is.',
  },

  // Newsletter: sign-up, confirmation, unsubscribe
  'Zu viele Versuche. Bitte warte ein paar Minuten.': {
    fr: 'Trop de tentatives. Veuillez patienter quelques minutes.',
    it: 'Troppi tentativi. Aspetta qualche minuto.',
    en: 'Too many attempts. Please wait a few minutes.',
  },
  'Bitte bestätige: Newsletter von {name}': { fr: 'Veuillez confirmer: newsletter de {name}', it: 'Conferma: newsletter di {name}', en: 'Please confirm: newsletter from {name}' },
  'jemand – hoffentlich du – möchte den Newsletter von {name} an diese Adresse bekommen.': {
    fr: 'quelqu’un – vous, espérons-le – souhaite recevoir la newsletter de {name} à cette adresse.',
    it: 'qualcuno – speriamo tu – vuole ricevere la newsletter di {name} a questo indirizzo.',
    en: 'someone – hopefully you – would like to receive the newsletter from {name} at this address.',
  },
  'Ein Klick bestätigt die Anmeldung:': { fr: 'Un clic confirme l’inscription:', it: 'Un clic conferma l’iscrizione:', en: 'One click confirms the subscription:' },
  'Anmeldung bestätigen': { fr: 'Confirmer l’inscription', it: 'Conferma l’iscrizione', en: 'Confirm subscription' },
  'Warst du das nicht? Dann ignoriere diese E-Mail einfach. Ohne Bestätigung schicken wir nichts.': {
    fr: 'Ce n’était pas vous? Ignorez simplement cet e-mail. Sans confirmation, nous n’envoyons rien.',
    it: 'Non sei stato tu? Allora ignora semplicemente questa e-mail. Senza conferma non inviamo nulla.',
    en: 'Wasn’t you? Then just ignore this email. Without confirmation we won’t send anything.',
  },
  'Link nicht mehr gültig': { fr: 'Lien plus valable', it: 'Link non più valido', en: 'Link no longer valid' },
  'Bestätigungslinks verfallen nach 30 Tagen. Melde dich einfach noch einmal an.': {
    fr: 'Les liens de confirmation expirent après 30 jours. Inscrivez-vous simplement à nouveau.',
    it: 'I link di conferma scadono dopo 30 giorni. Iscriviti semplicemente di nuovo.',
    en: 'Confirmation links expire after 30 days. Just sign up again.',
  },
  'Anmeldung bestätigt': { fr: 'Inscription confirmée', it: 'Iscrizione confermata', en: 'Subscription confirmed' },
  'Du bist schon dabei.': { fr: 'Vous êtes déjà inscrit.', it: 'Sei già iscritto.', en: 'You’re already subscribed.' },
  'Danke, du bist dabei!': { fr: 'Merci, vous êtes inscrit!', it: 'Grazie, sei iscritto!', en: 'Thanks, you’re in!' },
  'Ab jetzt bekommst du Neues von {name} an': {
    fr: 'Vous recevrez désormais les nouveautés de {name} à l’adresse',
    it: 'D’ora in poi riceverai le novità di {name} all’indirizzo',
    en: 'From now on you’ll get news from {name} at',
  },
  'Abmelden kannst du dich mit dem Link unten in jeder E-Mail.': {
    fr: 'Vous pouvez vous désabonner via le lien en bas de chaque e-mail.',
    it: 'Puoi disiscriverti con il link in fondo a ogni e-mail.',
    en: 'You can unsubscribe with the link at the bottom of every email.',
  },
  Abgemeldet: { fr: 'Désabonné', it: 'Disiscritto', en: 'Unsubscribed' },
  'Abgemeldet.': { fr: 'Désabonné.', it: 'Disiscritto.', en: 'Unsubscribed.' },
  'Du bist abgemeldet.': { fr: 'Vous êtes désabonné.', it: 'Ti sei disiscritto.', en: 'You’re unsubscribed.' },
  '{email} bekommt keinen Newsletter von {name} mehr. Schade – aber danke fürs Lesen.': {
    fr: '{email} ne recevra plus la newsletter de {name}. Dommage – mais merci de nous avoir lus.',
    it: '{email} non riceverà più la newsletter di {name}. Peccato, ma grazie per averci letto.',
    en: '{email} will no longer get the newsletter from {name}. A pity – but thanks for reading.',
  },
  'Doch wieder anmelden': { fr: 'Se réabonner', it: 'Iscriviti di nuovo', en: 'Subscribe again after all' },
  'Newsletter abmelden': { fr: 'Se désabonner de la newsletter', it: 'Disiscriviti dalla newsletter', en: 'Unsubscribe from the newsletter' },
  'Abmelden?': { fr: 'Se désabonner?', it: 'Disiscriverti?', en: 'Unsubscribe?' },
  '{email} bekommt dann keinen Newsletter von {name} mehr.': {
    fr: '{email} ne recevra alors plus la newsletter de {name}.',
    it: '{email} non riceverà più la newsletter di {name}.',
    en: '{email} will then no longer get the newsletter from {name}.',
  },
  'Ja, abmelden': { fr: 'Oui, me désabonner', it: 'Sì, disiscrivimi', en: 'Yes, unsubscribe' },
  'Bitte bestätigen': { fr: 'Veuillez confirmer', it: 'Conferma', en: 'Please confirm' },
  'Wir haben dir eine E-Mail geschickt. Ein Klick auf den Link darin, und du bist wieder dabei.': {
    fr: 'Nous vous avons envoyé un e-mail. Un clic sur le lien qu’il contient, et vous êtes à nouveau inscrit.',
    it: 'Ti abbiamo inviato un’e-mail. Un clic sul link al suo interno e sei di nuovo iscritto.',
    en: 'We’ve sent you an email. One click on the link in it and you’re back in.',
  },
};
