/** Website texts (events, courses, tickets, waitlist, donations), keyed by the German original. */
export const events: Record<string, { fr: string; it: string; en: string }> = {
  /* ---------- event and course pages, cards ---------- */
  Gratis: { fr: 'Gratuit', it: 'Gratuito', en: 'Free' },
  Abgesagt: { fr: 'Annulé', it: 'Annullato', en: 'Cancelled' },
  'Abgesagt.': { fr: 'Annulé.', it: 'Annullato.', en: 'Cancelled.' },
  Ausgebucht: { fr: 'Complet', it: 'Al completo', en: 'Fully booked' },
  'Ausgebucht.': { fr: 'Complet.', it: 'Al completo.', en: 'Fully booked.' },
  Ausverkauft: { fr: 'Complet', it: 'Esaurito', en: 'Sold out' },
  'Ausverkauft.': { fr: 'Complet.', it: 'Esaurito.', en: 'Sold out.' },
  'Noch {n} Platz': { fr: 'Plus que {n} place', it: 'Ancora {n} posto', en: '{n} place left' },
  'Noch {n} Plätze': { fr: 'Plus que {n} places', it: 'Ancora {n} posti', en: '{n} places left' },
  'Gerade sind keine Kurse ausgeschrieben.': {
    fr: 'Aucun cours n’est proposé pour le moment.',
    it: 'Al momento non ci sono corsi in programma.',
    en: 'There are no courses on offer right now.',
  },
  'Gerade sind keine Anlässe geplant.': {
    fr: 'Aucun événement n’est prévu pour le moment.',
    it: 'Al momento non ci sono eventi in programma.',
    en: 'There are no events planned right now.',
  },
  'Schau bald wieder vorbei.': { fr: 'Revenez bientôt.', it: 'Torna a trovarci presto.', en: 'Check back soon.' },
  '{n} Termine': { fr: '{n} dates', it: '{n} date', en: '{n} dates' },
  'ab {price}': { fr: 'dès {price}', it: 'da {price}', en: 'from {price}' },
  Termine: { fr: 'Dates', it: 'Date', en: 'Dates' },
  Wann: { fr: 'Quand', it: 'Quando', en: 'When' },
  'Datum folgt': { fr: 'Date à venir', it: 'Data da definire', en: 'Date to be announced' },
  Wo: { fr: 'Où', it: 'Dove', en: 'Where' },
  Leitung: { fr: 'Animation', it: 'Conduzione', en: 'Instructor' },
  Niveau: { fr: 'Niveau', it: 'Livello', en: 'Level' },
  Kosten: { fr: 'Prix', it: 'Costo', en: 'Cost' },
  Eintritt: { fr: 'Entrée', it: 'Ingresso', en: 'Admission' },
  'Dieser Kurs findet nicht statt.': { fr: 'Ce cours n’aura pas lieu.', it: 'Questo corso non si terrà.', en: 'This course will not take place.' },
  'Dieser Anlass findet nicht statt.': { fr: 'Cet événement n’aura pas lieu.', it: 'Questo evento non si terrà.', en: 'This event will not take place.' },
  'Anmelden|Kurs': { fr: 'S’inscrire', it: 'Iscriviti', en: 'Sign up' },
  Anmeldung: { fr: 'Inscription', it: 'Iscrizione', en: 'Registration' },
  Ticket: { fr: 'Billet', it: 'Biglietto', en: 'Ticket' },
  Tickets: { fr: 'Billets', it: 'Biglietti', en: 'Tickets' },
  'In den Kalender': { fr: 'Ajouter au calendrier', it: 'Aggiungi al calendario', en: 'Add to calendar' },

  /* ---------- ticket box and waitlist ---------- */
  'Abgesagt – keine Anmeldung möglich.': { fr: 'Annulé – inscription impossible.', it: 'Annullato – iscrizione non possibile.', en: 'Cancelled – registration is not possible.' },
  'Die Anmeldung ist geschlossen.': { fr: 'Les inscriptions sont closes.', it: 'Le iscrizioni sono chiuse.', en: 'Registration is closed.' },
  'Dieser Anlass hat bereits begonnen oder stattgefunden.': {
    fr: 'Cet événement a déjà commencé ou a déjà eu lieu.',
    it: 'Questo evento è già iniziato o si è già svolto.',
    en: 'This event has already started or taken place.',
  },
  'Du stehst auf der Warteliste. Wird ein Platz frei, schreiben wir dir sofort.': {
    fr: 'Vous êtes sur la liste d’attente. Si une place se libère, nous vous écrivons aussitôt.',
    it: 'Sei in lista d’attesa. Se si libera un posto, ti scriviamo subito.',
    en: 'You’re on the waiting list. If a place opens up, we’ll email you right away.',
  },
  'Trag dich in die Warteliste ein – wird ein Platz frei, bekommst du sofort eine E-Mail.': {
    fr: 'Inscrivez-vous sur la liste d’attente – si une place se libère, vous recevez aussitôt un e-mail.',
    it: 'Iscriviti alla lista d’attesa – se si libera un posto, ricevi subito un’e-mail.',
    en: 'Join the waiting list – if a place opens up, you’ll get an email right away.',
  },
  Name: { fr: 'Nom', it: 'Nome', en: 'Name' },
  'E-Mail': { fr: 'E-mail', it: 'E-mail', en: 'Email' },
  'Auf die Warteliste': { fr: 'M’inscrire sur la liste d’attente', it: 'Mettimi in lista d’attesa', en: 'Join the waiting list' },
  'Die Online-Anmeldung ist gerade nicht möglich.': {
    fr: 'L’inscription en ligne n’est pas possible pour le moment.',
    it: 'Al momento l’iscrizione online non è possibile.',
    en: 'Online registration isn’t available right now.',
  },
  'Schreib uns:': { fr: 'Écrivez-nous :', it: 'Scrivici:', en: 'Write to us:' },
  'Anzahl {name}': { fr: 'Quantité {name}', it: 'Quantità {name}', en: 'Quantity {name}' },
  'Weiter zur Zahlung': { fr: 'Continuer vers le paiement', it: 'Procedi al pagamento', en: 'Continue to payment' },
  'Verbindlich anmelden': { fr: 'S’inscrire définitivement', it: 'Iscriviti in modo vincolante', en: 'Register (binding)' },
  'Tickets bestellen': { fr: 'Commander des billets', it: 'Ordina i biglietti', en: 'Order tickets' },
  'Bezahlen mit TWINT, Karte, Apple Pay oder Google Pay.': {
    fr: 'Paiement par TWINT, carte, Apple Pay ou Google Pay.',
    it: 'Paga con TWINT, carta, Apple Pay o Google Pay.',
    en: 'Pay with TWINT, card, Apple Pay or Google Pay.',
  },
  'Die Bestätigung kommen per E-Mail.': { fr: 'La confirmation vous parvient par e-mail.', it: 'La conferma ti arriva via e-mail.', en: 'The confirmation will be sent by email.' },
  'Die Tickets kommen per E-Mail.': { fr: 'Les billets vous parviennent par e-mail.', it: 'I biglietti ti arrivano via e-mail.', en: 'The tickets will be sent by email.' },
  Datenschutz: { fr: 'Protection des données', it: 'Privacy', en: 'Privacy' },
  'Bitte leer lassen': { fr: 'Veuillez laisser vide', it: 'Lascia vuoto', en: 'Please leave empty' },
  'Zu viele Versuche. Bitte warte ein paar Minuten.': {
    fr: 'Trop de tentatives. Veuillez patienter quelques minutes.',
    it: 'Troppi tentativi. Aspetta qualche minuto.',
    en: 'Too many attempts. Please wait a few minutes.',
  },

  /* ---------- ticket orders: messages ---------- */
  '{n} Termine ab {date}': { fr: '{n} dates, dès le {date}', it: '{n} date, dal {date}', en: '{n} dates from {date}' },
  'Bitte gib deinen Namen an.': { fr: 'Veuillez indiquer votre nom.', it: 'Indica il tuo nome.', en: 'Please enter your name.' },
  'Bitte gib eine gültige E-Mail-Adresse an.': { fr: 'Veuillez indiquer une adresse e-mail valable.', it: 'Indica un indirizzo e-mail valido.', en: 'Please enter a valid email address.' },
  'Bitte gib eine gültige E-Mail-Adresse an – dorthin schicken wir die Tickets.': {
    fr: 'Veuillez indiquer une adresse e-mail valable – nous y enverrons les billets.',
    it: 'Indica un indirizzo e-mail valido – è lì che ti invieremo i biglietti.',
    en: 'Please enter a valid email address – that’s where we’ll send the tickets.',
  },
  'Dieser Anlass ist abgesagt.': { fr: 'Cet événement est annulé.', it: 'Questo evento è annullato.', en: 'This event has been cancelled.' },
  'Wähle mindestens ein Ticket.': { fr: 'Choisissez au moins un billet.', it: 'Scegli almeno un biglietto.', en: 'Choose at least one ticket.' },
  'Pro Bestellung gehen höchstens {max} Tickets.': { fr: 'Au maximum {max} billets par commande.', it: 'Al massimo {max} biglietti per ordine.', en: 'A maximum of {max} tickets per order.' },
  'Die Online-Zahlung ist gerade nicht eingerichtet. Melde dich bitte direkt bei uns.': {
    fr: 'Le paiement en ligne n’est pas disponible pour le moment. Veuillez nous contacter directement.',
    it: 'Al momento il pagamento online non è attivo. Contattaci direttamente.',
    en: 'Online payment isn’t set up right now. Please contact us directly.',
  },
  '«{name}» ist ausverkauft.': { fr: '«{name}» est complet.', it: '«{name}» è esaurito.', en: '“{name}” is sold out.' },
  'Für «{name}» sind nur noch {n} Plätze frei.': { fr: 'Il ne reste que {n} places pour «{name}».', it: 'Per «{name}» restano solo {n} posti.', en: 'Only {n} places left for “{name}”.' },
  'Die Zahlung konnte nicht gestartet werden: {error}': {
    fr: 'Le paiement n’a pas pu être lancé : {error}',
    it: 'Non è stato possibile avviare il pagamento: {error}',
    en: 'The payment could not be started: {error}',
  },

  /* ---------- ticket e-mails ---------- */
  'Hallo {name},': { fr: 'Bonjour {name},', it: 'Ciao {name},', en: 'Hi {name},' },
  'Hallo,': { fr: 'Bonjour,', it: 'Ciao,', en: 'Hi,' },
  'Dein Ticket: {title}': { fr: 'Votre billet : {title}', it: 'Il tuo biglietto: {title}', en: 'Your ticket: {title}' },
  'Deine Tickets: {title}': { fr: 'Vos billets : {title}', it: 'I tuoi biglietti: {title}', en: 'Your tickets: {title}' },
  'danke! Dein Platz ist reserviert:': { fr: 'Merci! Votre place est réservée :', it: 'grazie! Il tuo posto è riservato:', en: 'Thank you! Your place is reserved:' },
  'danke! Deine {n} Plätze sind reserviert:': { fr: 'Merci! Vos {n} places sont réservées :', it: 'grazie! I tuoi {n} posti sono riservati:', en: 'Thank you! Your {n} places are reserved:' },
  'Tickets mit QR-Code (zum Vorzeigen am Eingang oder Ausdrucken):': {
    fr: 'Billets avec code QR (à présenter à l’entrée ou à imprimer) :',
    it: 'Biglietti con codice QR (da mostrare all’ingresso o da stampare):',
    en: 'Tickets with QR code (show at the entrance or print):',
  },
  'Storniert: {title}': { fr: 'Annulé : {title}', it: 'Annullato: {title}', en: 'Cancelled: {title}' },
  'deine Tickets für «{title}» sind storniert.': {
    fr: 'Vos billets pour «{title}» ont été annulés.',
    it: 'i tuoi biglietti per «{title}» sono stati annullati.',
    en: 'Your tickets for “{title}” have been cancelled.',
  },
  'Eine Rückzahlung erhältst du auf dem gleichen Weg, wie du bezahlt hast.': {
    fr: 'Le remboursement sera effectué par le même moyen que votre paiement.',
    it: 'Riceverai il rimborso con lo stesso metodo con cui hai pagato.',
    en: 'You’ll be refunded the same way you paid.',
  },
  'Ein Platz ist frei: {title}': { fr: 'Une place s’est libérée : {title}', it: 'Si è liberato un posto: {title}', en: 'A place is available: {title}' },
  'für «{title}» ({when}) ist wieder ein Platz frei. Wer zuerst kommt …': {
    fr: 'Une place s’est libérée pour «{title}» ({when}). Premier arrivé, premier servi …',
    it: 'per «{title}» ({when}) si è liberato un posto. Chi prima arriva …',
    en: 'A place has opened up for “{title}” ({when}). First come, first served …',
  },

  /* ---------- buyer's ticket page ---------- */
  'Die Zahlung wurde abgebrochen, die Plätze sind wieder frei.': {
    fr: 'Le paiement a été interrompu, les places sont à nouveau libres.',
    it: 'Il pagamento è stato annullato, i posti sono di nuovo liberi.',
    en: 'The payment was cancelled; the places have been released.',
  },
  'Diese Bestellung ist storniert.': { fr: 'Cette commande est annulée.', it: 'Questo ordine è stato annullato.', en: 'This order has been cancelled.' },
  'Die Zahlung wurde abgebrochen.': { fr: 'Le paiement a été interrompu.', it: 'Il pagamento è stato interrotto.', en: 'The payment was cancelled.' },
  'Die Zahlung ist noch offen.': { fr: 'Le paiement est encore en attente.', it: 'Il pagamento è ancora in sospeso.', en: 'The payment is still outstanding.' },
  'Die Plätze bleiben 30 Minuten für dich reserviert.': {
    fr: 'Les places vous sont réservées pendant 30 minutes.',
    it: 'I posti restano riservati per te per 30 minuti.',
    en: 'Your places are held for 30 minutes.',
  },
  '{amount} bezahlen': { fr: 'Payer {amount}', it: 'Paga {amount}', en: 'Pay {amount}' },
  'Danke!': { fr: 'Merci!', it: 'Grazie!', en: 'Thank you!' },
  'Deine Anmeldung ist bestätigt.': { fr: 'Votre inscription est confirmée.', it: 'La tua iscrizione è confermata.', en: 'Your registration is confirmed.' },
  'Hier ist dein Ticket.': { fr: 'Voici votre billet.', it: 'Ecco il tuo biglietto.', en: 'Here is your ticket.' },
  'Hier sind deine Tickets.': { fr: 'Voici vos billets.', it: 'Ecco i tuoi biglietti.', en: 'Here are your tickets.' },
  'Wir haben es dir auch per E-Mail geschickt.': { fr: 'Nous vous l’avons aussi envoyé par e-mail.', it: 'Te l’abbiamo inviato anche via e-mail.', en: 'We’ve also sent it to you by email.' },
  'Wir haben sie dir auch per E-Mail geschickt.': { fr: 'Nous vous les avons aussi envoyés par e-mail.', it: 'Te li abbiamo inviati anche via e-mail.', en: 'We’ve also sent them to you by email.' },
  'QR-Code für Ticket {code}': { fr: 'Code QR du billet {code}', it: 'Codice QR del biglietto {code}', en: 'QR code for ticket {code}' },
  Eingelöst: { fr: 'Utilisé', it: 'Utilizzato', en: 'Used' },
  '{n} von {total}': { fr: '{n} sur {total}', it: '{n} di {total}', en: '{n} of {total}' },
  Drucken: { fr: 'Imprimer', it: 'Stampa', en: 'Print' },
  'Am Eingang den QR-Code zeigen – auf dem Handy oder ausgedruckt.': {
    fr: 'Présentez le code QR à l’entrée – sur votre téléphone ou imprimé.',
    it: 'Mostra il codice QR all’ingresso – sul telefono o stampato.',
    en: 'Show the QR code at the entrance – on your phone or printed.',
  },
  'Bezahlt: {amount}.': { fr: 'Payé : {amount}.', it: 'Pagato: {amount}.', en: 'Paid: {amount}.' },
  'Fragen?': { fr: 'Des questions ?', it: 'Domande?', en: 'Questions?' },

  /* ---------- donate block ---------- */
  Spendenziel: { fr: 'Objectif de dons', it: 'Obiettivo di raccolta', en: 'Donation goal' },
  'von {amount}': { fr: 'sur {amount}', it: 'su {amount}', en: 'of {amount}' },
  gesammelt: { fr: 'collectés', it: 'raccolti', en: 'raised' },
  '{n} Person hat gespendet': { fr: '{n} personne a fait un don', it: '{n} persona ha donato', en: '{n} person has donated' },
  '{n} Personen haben gespendet': { fr: '{n} personnes ont fait un don', it: '{n} persone hanno donato', en: '{n} people have donated' },
  'Per Überweisung': { fr: 'Par virement', it: 'Tramite bonifico', en: 'By bank transfer' },
  'Vermerk: {campaign}': { fr: 'Communication : {campaign}', it: 'Comunicazione: {campaign}', en: 'Reference: {campaign}' },
  'Einzahlungsschein mit QR-Code': { fr: 'Bulletin de versement avec code QR', it: 'Polizza di versamento con codice QR', en: 'Payment slip with QR code' },
  'Wie oft?': { fr: 'À quelle fréquence?', it: 'Con quale frequenza?', en: 'How often?' },
  Einmalig: { fr: 'Unique', it: 'Una tantum', en: 'One-time' },
  Monatlich: { fr: 'Mensuel', it: 'Mensile', en: 'Monthly' },
  Betrag: { fr: 'Montant', it: 'Importo', en: 'Amount' },
  'Anderer Betrag in {currency}': { fr: 'Autre montant en {currency}', it: 'Altro importo in {currency}', en: 'Other amount in {currency}' },
  'Anderer Betrag': { fr: 'Autre montant', it: 'Altro importo', en: 'Other amount' },
  'Adresse für die Spendenbestätigung (fürs Steueramt)': {
    fr: 'Adresse pour l’attestation de don (pour les impôts)',
    it: 'Indirizzo per l’attestazione di donazione (per le imposte)',
    en: 'Address for the donation receipt (for your tax return)',
  },
  Strasse: { fr: 'Rue', it: 'Via', en: 'Street' },
  PLZ: { fr: 'NPA', it: 'NPA', en: 'Postcode' },
  Ort: { fr: 'Localité', it: 'Località', en: 'Town' },
  'Meinen Namen nicht öffentlich nennen': { fr: 'Ne pas publier mon nom', it: 'Non pubblicare il mio nome', en: 'Don’t show my name publicly' },
  'Jetzt spenden': { fr: 'Faire un don', it: 'Dona ora', en: 'Donate now' },
  'Sicher über Stripe: TWINT, Karte, Apple Pay, Google Pay.': {
    fr: 'Paiement sécurisé via Stripe : TWINT, carte, Apple Pay, Google Pay.',
    it: 'Pagamento sicuro tramite Stripe: TWINT, carta, Apple Pay, Google Pay.',
    en: 'Secure via Stripe: TWINT, card, Apple Pay, Google Pay.',
  },
  'Monatliche Spenden lassen sich jederzeit mit einem Klick beenden.': {
    fr: 'Les dons mensuels peuvent être arrêtés à tout moment en un clic.',
    it: 'Le donazioni mensili si possono interrompere in qualsiasi momento con un clic.',
    en: 'Monthly donations can be stopped at any time with one click.',
  },
  'Lieber per Überweisung?': { fr: 'Vous préférez un virement?', it: 'Preferisci un bonifico?', en: 'Prefer a bank transfer?' },

  /* ---------- donations: messages and e-mails ---------- */
  'Online-Spenden sind gerade nicht eingerichtet. Danke, wenn du per Überweisung spendest!': {
    fr: 'Les dons en ligne ne sont pas disponibles pour le moment. Merci de faire votre don par virement!',
    it: 'Al momento le donazioni online non sono attive. Grazie se doni tramite bonifico!',
    en: 'Online donations aren’t set up right now. Thank you for donating by bank transfer instead!',
  },
  'Online geht es ab {min} – darunter fressen die Gebühren die Spende auf.': {
    fr: 'En ligne, le don minimum est de {min} – en dessous, les frais absorbent le don.',
    it: 'Online si dona a partire da {min} – sotto questa cifra le commissioni si mangiano la donazione.',
    en: 'Online donations start at {min} – below that, fees eat up the donation.',
  },
  'Für so grosse Beträge melde dich bitte direkt bei uns. Danke!': {
    fr: 'Pour un montant aussi important, veuillez nous contacter directement. Merci!',
    it: 'Per importi così grandi contattaci direttamente. Grazie!',
    en: 'For amounts this large, please contact us directly. Thank you!',
  },
  'Bitte gib eine gültige E-Mail-Adresse an – für die Bestätigung.': {
    fr: 'Veuillez indiquer une adresse e-mail valable – pour la confirmation.',
    it: 'Indica un indirizzo e-mail valido – per la conferma.',
    en: 'Please enter a valid email address – for the confirmation.',
  },
  Spende: { fr: 'Don', it: 'Donazione', en: 'Donation' },
  'Danke für deine Spende an {name}': { fr: 'Merci pour votre don à {name}', it: 'Grazie per la tua donazione a {name}', en: 'Thank you for your donation to {name}' },
  'Monatliche Spende: {amount} – danke!': { fr: 'Don mensuel : {amount} – merci!', it: 'Donazione mensile: {amount} – grazie!', en: 'Monthly donation: {amount} – thank you!' },
  'herzlichen Dank für deine Spende von {amount}. Sie kommt an.': {
    fr: 'Merci beaucoup pour votre don de {amount}. Il arrive à bon port.',
    it: 'grazie di cuore per la tua donazione di {amount}. Arriva a buon fine.',
    en: 'Thank you so much for your donation of {amount}. It’s in good hands.',
  },
  'herzlichen Dank für deine Spende von {amount} für «{campaign}». Sie kommt an.': {
    fr: 'Merci beaucoup pour votre don de {amount} pour «{campaign}». Il arrive à bon port.',
    it: 'grazie di cuore per la tua donazione di {amount} per «{campaign}». Arriva a buon fine.',
    en: 'Thank you so much for your donation of {amount} for “{campaign}”. It’s in good hands.',
  },
  'herzlichen Dank für deine monatliche Spende von {amount}. Sie kommt an.': {
    fr: 'Merci beaucoup pour votre don mensuel de {amount}. Il arrive à bon port.',
    it: 'grazie di cuore per la tua donazione mensile di {amount}. Arriva a buon fine.',
    en: 'Thank you so much for your monthly donation of {amount}. It’s in good hands.',
  },
  'herzlichen Dank für deine monatliche Spende von {amount} für «{campaign}». Sie kommt an.': {
    fr: 'Merci beaucoup pour votre don mensuel de {amount} pour «{campaign}». Il arrive à bon port.',
    it: 'grazie di cuore per la tua donazione mensile di {amount} per «{campaign}». Arriva a buon fine.',
    en: 'Thank you so much for your monthly donation of {amount} for “{campaign}”. It’s in good hands.',
  },
  'auch diesen Monat sind {amount} bei uns angekommen. Danke, dass du dabei bleibst.': {
    fr: 'Ce mois-ci aussi, {amount} nous sont parvenus. Merci de votre fidélité.',
    it: 'anche questo mese ci sono arrivati {amount}. Grazie perché continui a sostenerci.',
    en: '{amount} reached us again this month. Thank you for staying with us.',
  },
  'Bestätigung: {url}': { fr: 'Confirmation : {url}', it: 'Conferma: {url}', en: 'Confirmation: {url}' },
  'Bestätigung und Verwaltung deiner monatlichen Spende: {url}': {
    fr: 'Confirmation et gestion de votre don mensuel : {url}',
    it: 'Conferma e gestione della tua donazione mensile: {url}',
    en: 'Confirmation and management of your monthly donation: {url}',
  },
  'Eine Spendenbestätigung fürs Steueramt kannst du dort ausdrucken; Anfang Jahr schicken wir gern eine fürs ganze Jahr.': {
    fr: 'Vous pouvez y imprimer une attestation de don pour votre déclaration d’impôts; en début d’année, nous vous en envoyons volontiers une pour toute l’année.',
    it: 'Lì puoi stampare un’attestazione di donazione per la dichiarazione d’imposta; a inizio anno te ne inviamo volentieri una per tutto l’anno.',
    en: 'You can print a donation receipt for your tax return there; at the start of the year we’re happy to send you one for the whole year.',
  },
  'Diese Spende läuft nicht monatlich.': { fr: 'Ce don n’est pas mensuel.', it: 'Questa donazione non è mensile.', en: 'This isn’t a monthly donation.' },
  'Das hat nicht geklappt. Bitte versuch es später nochmals oder schreib uns.': {
    fr: 'Cela n’a pas fonctionné. Veuillez réessayer plus tard ou nous écrire.',
    it: 'Non ha funzionato. Riprova più tardi o scrivici.',
    en: 'That didn’t work. Please try again later or write to us.',
  },

  /* ---------- donor's page, payment slip ---------- */
  Einzahlungsschein: { fr: 'Bulletin de versement', it: 'Polizza di versamento', en: 'Payment slip' },
  'Danke für deine Spende!': { fr: 'Merci pour votre don!', it: 'Grazie per la tua donazione!', en: 'Thank you for your donation!' },
  'Scanne den QR-Code mit deiner Banking-App oder drucke den Einzahlungsschein aus. Den Betrag wählst du selbst.': {
    fr: 'Scannez le code QR avec votre application bancaire ou imprimez le bulletin de versement. Vous choisissez vous-même le montant.',
    it: 'Scansiona il codice QR con la tua app bancaria o stampa la polizza di versamento. L’importo lo scegli tu.',
    en: 'Scan the QR code with your banking app or print the payment slip. You choose the amount.',
  },
  'Deine monatliche Spende von {amount} läuft.': { fr: 'Votre don mensuel de {amount} est actif.', it: 'La tua donazione mensile di {amount} è attiva.', en: 'Your monthly donation of {amount} is active.' },
  'Deine monatliche Spende ist beendet. Danke für alles!': {
    fr: 'Votre don mensuel est arrêté. Merci pour tout!',
    it: 'La tua donazione mensile è terminata. Grazie di tutto!',
    en: 'Your monthly donation has ended. Thank you for everything!',
  },
  'Deine Spende von {amount} ist angekommen.': { fr: 'Votre don de {amount} nous est bien parvenu.', it: 'La tua donazione di {amount} è arrivata.', en: 'Your donation of {amount} has arrived.' },
  'Die Zahlung wurde abgebrochen – es wurde nichts belastet.': {
    fr: 'Le paiement a été interrompu – rien n’a été débité.',
    it: 'Il pagamento è stato annullato – non è stato addebitato nulla.',
    en: 'The payment was cancelled – nothing was charged.',
  },
  'Die Zahlung wird noch bestätigt. Das dauert meist nur Sekunden – lade die Seite gleich nochmals.': {
    fr: 'Le paiement est en cours de confirmation. Cela ne prend généralement que quelques secondes – rechargez la page dans un instant.',
    it: 'Il pagamento è in fase di conferma. Di solito bastano pochi secondi – ricarica la pagina tra un attimo.',
    en: 'The payment is still being confirmed. This usually takes just a few seconds – reload the page in a moment.',
  },
  'Diese Spende wurde nicht abgeschlossen.': { fr: 'Ce don n’a pas été finalisé.', it: 'Questa donazione non è stata completata.', en: 'This donation was not completed.' },
  'Spende an {name}': { fr: 'Don à {name}', it: 'Donazione a {name}', en: 'Donation to {name}' },
  'Herzlichen Dank': { fr: 'Merci beaucoup', it: 'Grazie di cuore', en: 'Thank you so much' },
  'Deine Spende': { fr: 'Votre don', it: 'La tua donazione', en: 'Your donation' },
  'pro Monat': { fr: 'par mois', it: 'al mese', en: 'per month' },
  Für: { fr: 'Pour', it: 'Per', en: 'For' },
  Bisher: { fr: 'Jusqu’ici', it: 'Finora', en: 'So far' },
  '{n} Monat': { fr: '{n} mois', it: '{n} mese', en: '{n} month' },
  '{n} Monate': { fr: '{n} mois', it: '{n} mesi', en: '{n} months' },
  'Monatliche Spende beenden': { fr: 'Arrêter le don mensuel', it: 'Interrompi la donazione mensile', en: 'Stop monthly donation' },
  'Ab nächstem Monat wird nichts mehr abgebucht. Bisherige Spenden bleiben – danke dafür!': {
    fr: 'Dès le mois prochain, plus rien ne sera débité. Les dons déjà versés restent acquis – merci pour eux!',
    it: 'Dal prossimo mese non verrà più addebitato nulla. Le donazioni fatte finora restano – grazie!',
    en: 'Nothing more will be charged from next month. Past donations remain – thank you for them!',
  },
  'Ja, beenden': { fr: 'Oui, arrêter', it: 'Sì, interrompi', en: 'Yes, stop' },
  'Nein, weiter spenden': { fr: 'Non, continuer à donner', it: 'No, continua a donare', en: 'No, keep donating' },

  /* ---------- donation receipt (Spendenbestätigung) ---------- */
  Spendenbestätigung: { fr: 'Attestation de don', it: 'Attestazione di donazione', en: 'Donation receipt' },
  'Drucken oder als PDF sichern': { fr: 'Imprimer ou enregistrer en PDF', it: 'Stampa o salva come PDF', en: 'Print or save as PDF' },
  'am {date}': { fr: 'le {date}', it: 'il {date}', en: 'on {date}' },
  'im Jahr {year}': { fr: 'au cours de l’année {year}', it: 'nell’anno {year}', en: 'in {year}' },
  'Wir bestätigen mit Dank, dass {donor} {when} folgende Spende an {recipient} geleistet hat:': {
    fr: 'Nous attestons avec reconnaissance que {donor} a versé {when} le don suivant à {recipient} :',
    it: 'Attestiamo con gratitudine che {donor} {when} ha effettuato la seguente donazione a {recipient}:',
    en: 'We gratefully confirm that {donor} made the following donation to {recipient} {when}:',
  },
  'Wir bestätigen mit Dank, dass {donor} {when} folgende Spenden an {recipient} geleistet hat:': {
    fr: 'Nous attestons avec reconnaissance que {donor} a versé {when} les dons suivants à {recipient} :',
    it: 'Attestiamo con gratitudine che {donor} {when} ha effettuato le seguenti donazioni a {recipient}:',
    en: 'We gratefully confirm that {donor} made the following donations to {recipient} {when}:',
  },
  Datum: { fr: 'Date', it: 'Data', en: 'Date' },
  Total: { fr: 'Total', it: 'Totale', en: 'Total' },
  'Verwendungszweck: {campaign}': { fr: 'Affectation : {campaign}', it: 'Destinazione: {campaign}', en: 'Purpose: {campaign}' },
  'Es wurden keine Gegenleistungen erbracht.': {
    fr: 'Aucune contrepartie n’a été fournie.',
    it: 'Non è stata fornita alcuna controprestazione.',
    en: 'No goods or services were provided in return.',
  },
};
