/** Website texts (services): real estate, food ordering & delivery, reservations & appointments. Keyed by the German original. */
export const services: Record<string, { fr: string; it: string; en: string }> = {
  // Real estate: list, filter, cards
  'Objekte filtern': { fr: 'Filtrer les biens', it: 'Filtra gli immobili', en: 'Filter properties' },
  Angebot: { fr: 'Offre', it: 'Offerta', en: 'Offer' },
  'Miete & Kauf': { fr: 'À louer et à vendre', it: 'In affitto e in vendita', en: 'For rent & for sale' },
  Miete: { fr: 'À louer', it: 'In affitto', en: 'For rent' },
  Kauf: { fr: 'À vendre', it: 'In vendita', en: 'For sale' },
  Art: { fr: 'Type', it: 'Tipo', en: 'Type' },
  Alle: { fr: 'Tous', it: 'Tutti', en: 'All' },
  Wohnung: { fr: 'Appartement', it: 'Appartamento', en: 'Apartment' },
  Haus: { fr: 'Maison', it: 'Casa', en: 'House' },
  'Zimmer / WG': { fr: 'Chambre / colocation', it: 'Camera / appartamento condiviso', en: 'Room / flatshare' },
  'Büro & Gewerbe': { fr: 'Bureau et commerce', it: 'Ufficio e commercio', en: 'Office & commercial' },
  'Parkplatz / Garage': { fr: 'Place de parc / garage', it: 'Posteggio / autorimessa', en: 'Parking space / garage' },
  Grundstück: { fr: 'Terrain', it: 'Terreno', en: 'Land' },
  Verfügbar: { fr: 'Disponible', it: 'Disponibile', en: 'Available' },
  Reserviert: { fr: 'Réservé', it: 'Riservato', en: 'Reserved' },
  'Vermietet / verkauft': { fr: 'Loué / vendu', it: 'Affittato / venduto', en: 'Rented / sold' },
  'Zimmer ab': { fr: 'Pièces dès', it: 'Locali da', en: 'Rooms from' },
  egal: { fr: 'indifférent', it: 'indifferente', en: 'any' },
  'Preis bis': { fr: 'Prix max.', it: 'Prezzo fino a', en: 'Max. price' },
  'Ort oder PLZ': { fr: 'Localité ou NPA', it: 'Località o NPA', en: 'Town or postcode' },
  Suchen: { fr: 'Rechercher', it: 'Cerca', en: 'Search' },
  Zurücksetzen: { fr: 'Réinitialiser', it: 'Reimposta', en: 'Reset' },
  '{n} Objekt': { fr: '{n} bien', it: '{n} immobile', en: '{n} property' },
  '{n} Objekte': { fr: '{n} biens', it: '{n} immobili', en: '{n} properties' },
  'Mit diesen Filtern passt gerade nichts. Lockere die Suche – oder lass dich benachrichtigen, wenn etwas Passendes kommt:': { fr: 'Aucun bien ne correspond à ces filtres pour le moment. Élargissez votre recherche – ou demandez-nous de vous avertir dès qu’un bien adapté se présente :', it: 'Al momento nessun immobile corrisponde a questi filtri. Allarga la ricerca – oppure fatti avvisare quando arriva qualcosa di adatto:', en: 'Nothing matches these filters right now. Widen your search – or get notified when something suitable comes up:' },
  'Gerade ist alles vergeben.': { fr: 'Aucun bien n’est disponible pour le moment.', it: 'Al momento non c’è nulla di disponibile.', en: 'Everything is taken right now.' },
  'Schreib uns': { fr: 'Écrivez-nous', it: 'Scrivici', en: 'Write to us' },
  '{n} Objekte von {name}.': { fr: '{n} biens de {name}.', it: '{n} immobili di {name}.', en: '{n} properties from {name}.' },
  '{n} Objekte von {name} in {city}.': { fr: '{n} biens de {name} à {city}.', it: '{n} immobili di {name} a {city}.', en: '{n} properties from {name} in {city}.' },
  '{n} Zi.': { fr: '{n} pièces', it: '{n} locali', en: '{n} rooms' },
  'Preis auf Anfrage': { fr: 'Prix sur demande', it: 'Prezzo su richiesta', en: 'Price on request' },
  '{price} / Mt.': { fr: '{price} / mois', it: '{price} / mese', en: '{price} / month' },
  // Real estate: detail page and enquiry
  Zimmer: { fr: 'Pièces', it: 'Locali', en: 'Rooms' },
  Fläche: { fr: 'Surface', it: 'Superficie', en: 'Floor area' },
  Etage: { fr: 'Étage', it: 'Piano', en: 'Floor' },
  Baujahr: { fr: 'Année de construction', it: 'Anno di costruzione', en: 'Year built' },
  Bezug: { fr: 'Entrée', it: 'Entrata', en: 'Move-in' },
  'Miete brutto': { fr: 'Loyer brut', it: 'Affitto lordo', en: 'Gross rent' },
  Preis: { fr: 'Prix', it: 'Prezzo', en: 'Price' },
  Nebenkosten: { fr: 'Charges', it: 'Spese accessorie', en: 'Utilities' },
  Adresse: { fr: 'Adresse', it: 'Indirizzo', en: 'Address' },
  'Reserviert – du kannst dich trotzdem melden, falls es nicht klappt.': { fr: 'Réservé – vous pouvez quand même nous contacter, au cas où cela ne se ferait pas.', it: 'Riservato – puoi comunque contattarci, nel caso non vada in porto.', en: 'Reserved – you can still get in touch in case it falls through.' },
  'Bereits vermietet.': { fr: 'Déjà loué.', it: 'Già affittato.', en: 'Already rented.' },
  'Bereits verkauft.': { fr: 'Déjà vendu.', it: 'Già venduto.', en: 'Already sold.' },
  Ausstattung: { fr: 'Équipement', it: 'Dotazioni', en: 'Features' },
  'Balkon / Terrasse': { fr: 'Balcon / terrasse', it: 'Balcone / terrazza', en: 'Balcony / terrace' },
  'Garten / Sitzplatz': { fr: 'Jardin / coin extérieur', it: 'Giardino / spazio esterno', en: 'Garden / patio' },
  Lift: { fr: 'Ascenseur', it: 'Ascensore', en: 'Lift' },
  'Eigene Waschmaschine': { fr: 'Lave-linge privatif', it: 'Lavatrice privata', en: 'Own washing machine' },
  'Haustiere erlaubt': { fr: 'Animaux admis', it: 'Animali ammessi', en: 'Pets allowed' },
  Rollstuhlgängig: { fr: 'Accessible en fauteuil roulant', it: 'Accessibile in sedia a rotelle', en: 'Wheelchair accessible' },
  Minergie: { fr: 'Minergie', it: 'Minergie', en: 'Minergie' },
  Aussicht: { fr: 'Vue', it: 'Vista', en: 'View' },
  Möbliert: { fr: 'Meublé', it: 'Arredato', en: 'Furnished' },
  Cheminée: { fr: 'Cheminée', it: 'Camino', en: 'Fireplace' },
  'Neubau / Erstbezug': { fr: 'Neuf / première location', it: 'Nuova costruzione / primo utilizzo', en: 'New build / first occupancy' },
  'Dokumentation herunterladen (PDF)': { fr: 'Télécharger la documentation (PDF)', it: 'Scarica la documentazione (PDF)', en: 'Download documentation (PDF)' },
  'Interessiert?': { fr: 'Ce bien vous intéresse?', it: 'Ti interessa?', en: 'Interested?' },
  'Danke! Wir melden uns so bald wie möglich.': { fr: 'Merci! Nous vous répondrons dès que possible.', it: 'Grazie! Ti risponderemo il prima possibile.', en: 'Thank you! We’ll get back to you as soon as possible.' },
  Nachricht: { fr: 'Message', it: 'Messaggio', en: 'Message' },
  'Ich interessiere mich für «{title}».': { fr: 'Je m’intéresse à «{title}».', it: 'Mi interessa «{title}».', en: 'I’m interested in “{title}”.' },
  'Ich möchte das Objekt besichtigen': { fr: 'Je souhaite visiter le bien', it: 'Vorrei visitare l’immobile', en: 'I’d like to view the property' },
  'Anfrage senden': { fr: 'Envoyer la demande', it: 'Invia richiesta', en: 'Send enquiry' },
  'Deine Angaben verwenden wir nur für diese Anfrage.': { fr: 'Nous utilisons vos données uniquement pour cette demande.', it: 'Usiamo i tuoi dati solo per questa richiesta.', en: 'We only use your details for this enquiry.' },
  'Oder ruf an:': { fr: 'Ou appelez-nous :', it: 'Oppure chiamaci:', en: 'Or call us:' },
  Zurück: { fr: 'Retour', it: 'Indietro', en: 'Back' },
  'Alle Objekte': { fr: 'Tous les biens', it: 'Tutti gli immobili', en: 'All properties' },
  'Zu viele Anfragen. Bitte warte ein paar Minuten.': { fr: 'Trop de demandes. Veuillez patienter quelques minutes.', it: 'Troppe richieste. Attendi qualche minuto.', en: 'Too many requests. Please wait a few minutes.' },
  // Forms (shared by enquiry, order and booking)
  'Bitte leer lassen': { fr: 'Merci de laisser vide', it: 'Lascia vuoto', en: 'Please leave empty' },
  Name: { fr: 'Nom', it: 'Nome', en: 'Name' },
  'E-Mail': { fr: 'E-mail', it: 'E-mail', en: 'Email' },
  Telefon: { fr: 'Téléphone', it: 'Telefono', en: 'Phone' },
  '(freiwillig)': { fr: '(facultatif)', it: '(facoltativo)', en: '(optional)' },
  Bemerkung: { fr: 'Remarque', it: 'Osservazioni', en: 'Note' },
  Datenschutz: { fr: 'Protection des données', it: 'Protezione dei dati', en: 'Privacy' },
  'Fragen?': { fr: 'Des questions?', it: 'Domande?', en: 'Questions?' },
  Wo: { fr: 'Où', it: 'Dove', en: 'Where' },
  'Bitte gib deinen Namen an.': { fr: 'Veuillez indiquer votre nom.', it: 'Indica il tuo nome.', en: 'Please enter your name.' },
  'Bitte gib eine gültige E-Mail-Adresse an.': { fr: 'Veuillez indiquer une adresse e-mail valide.', it: 'Indica un indirizzo e-mail valido.', en: 'Please enter a valid email address.' },
  'Zu viele Versuche. Bitte warte ein paar Minuten.': { fr: 'Trop de tentatives. Veuillez patienter quelques minutes.', it: 'Troppi tentativi. Attendi qualche minuto.', en: 'Too many attempts. Please wait a few minutes.' },
  'Hallo {name},': { fr: 'Bonjour {name},', it: 'Ciao {name},', en: 'Hi {name},' },
  '{when} Uhr': { fr: '{when}', it: '{when}', en: '{when}' },
  // Food ordering: menu and cart
  'Online bestellen': { fr: 'Commander en ligne', it: 'Ordina online', en: 'Order online' },
  'Online bestellen bei {name}': { fr: 'Commander en ligne chez {name}', it: 'Ordina online da {name}', en: 'Order online from {name}' },
  'Take-away und Lieferung von {name}': { fr: 'À l’emporter et livraison de {name}', it: 'Take-away e consegna di {name}', en: 'Takeaway and delivery from {name}' },
  'Deine Bestellung': { fr: 'Votre commande', it: 'Il tuo ordine', en: 'Your order' },
  'Noch leer. Tipp auf «+» bei einem Gericht.': { fr: 'Encore vide. Appuyez sur «+» à côté d’un plat.', it: 'Ancora vuoto. Tocca «+» accanto a un piatto.', en: 'Still empty. Tap “+” next to a dish.' },
  'Eins weniger: {dish}': { fr: 'Un de moins : {dish}', it: 'Uno in meno: {dish}', en: 'One less: {dish}' },
  'Eins mehr: {dish}': { fr: 'Un de plus : {dish}', it: 'Uno in più: {dish}', en: 'One more: {dish}' },
  Zwischensumme: { fr: 'Sous-total', it: 'Subtotale', en: 'Subtotal' },
  'Lieferung {fee}, ab {min} Bestellwert.': { fr: 'Livraison {fee}, dès {min} de commande.', it: 'Consegna {fee}, con un ordine minimo di {min}.', en: 'Delivery {fee}, minimum order {min}.' },
  'Weiter zur Bestellung': { fr: 'Passer à la commande', it: 'Procedi all’ordine', en: 'Continue to checkout' },
  Weiteres: { fr: 'Autres', it: 'Altro', en: 'Other' },
  Abholen: { fr: 'À l’emporter', it: 'Ritiro', en: 'Pickup' },
  'Liefern lassen': { fr: 'Livraison', it: 'Consegna a domicilio', en: 'Delivery' },
  '{a} oder {b}': { fr: '{a} / {b}', it: '{a} / {b}', en: '{a} / {b}' },
  '{modes} · frühestens {day} {time} Uhr': { fr: '{modes} · au plus tôt {day} à {time}', it: '{modes} · al più presto {day} alle {time}', en: '{modes} · earliest {day} at {time}' },
  'Die Küche ist gerade voll und nimmt keine neuen Bestellungen an. Bitte versuch es etwas später.': { fr: 'La cuisine est complète et ne prend pas de nouvelles commandes pour le moment. Veuillez réessayer un peu plus tard.', it: 'La cucina è al completo e al momento non accetta nuovi ordini. Riprova un po’ più tardi.', en: 'The kitchen is full and isn’t taking new orders right now. Please try again a little later.' },
  'Gerade sind keine Bestellungen möglich – schau während der Öffnungszeiten wieder vorbei.': { fr: 'Aucune commande n’est possible pour le moment – revenez pendant nos heures d’ouverture.', it: 'Al momento non è possibile ordinare – torna durante gli orari di apertura.', en: 'Orders aren’t possible right now – come back during opening hours.' },
  '{dish} ist in deiner Bestellung.': { fr: '{dish} est dans votre commande.', it: '{dish} è nel tuo ordine.', en: '{dish} is in your order.' },
  Ansehen: { fr: 'Voir', it: 'Vedi', en: 'View' },
  'Allergene: {list}': { fr: 'Allergènes : {list}', it: 'Allergeni: {list}', en: 'Allergens: {list}' },
  'Heute ausverkauft': { fr: 'Épuisé aujourd’hui', it: 'Esaurito oggi', en: 'Sold out today' },
  '{dish} hinzufügen, {price}': { fr: 'Ajouter {dish}, {price}', it: 'Aggiungi {dish}, {price}', en: 'Add {dish}, {price}' },
  'Bestellung ansehen': { fr: 'Voir la commande', it: 'Vedi l’ordine', en: 'View order' },
  Gluten: { fr: 'Gluten', it: 'Glutine', en: 'Gluten' },
  Krebstiere: { fr: 'Crustacés', it: 'Crostacei', en: 'Crustaceans' },
  Ei: { fr: 'Œuf', it: 'Uovo', en: 'Egg' },
  Fisch: { fr: 'Poisson', it: 'Pesce', en: 'Fish' },
  Erdnuss: { fr: 'Arachide', it: 'Arachidi', en: 'Peanut' },
  Soja: { fr: 'Soja', it: 'Soia', en: 'Soy' },
  Milch: { fr: 'Lait', it: 'Latte', en: 'Milk' },
  Nüsse: { fr: 'Fruits à coque', it: 'Frutta a guscio', en: 'Nuts' },
  Sellerie: { fr: 'Céleri', it: 'Sedano', en: 'Celery' },
  Senf: { fr: 'Moutarde', it: 'Senape', en: 'Mustard' },
  Sesam: { fr: 'Sésame', it: 'Sesamo', en: 'Sesame' },
  Sulfite: { fr: 'Sulfites', it: 'Solfiti', en: 'Sulphites' },
  Lupinen: { fr: 'Lupin', it: 'Lupini', en: 'Lupin' },
  Weichtiere: { fr: 'Mollusques', it: 'Molluschi', en: 'Molluscs' },
  // Food ordering: checkout
  '← Zur Karte': { fr: '← Retour au menu', it: '← Torna al menu', en: '← Back to the menu' },
  Bestellen: { fr: 'Commander', it: 'Ordina', en: 'Order' },
  'Wie?': { fr: 'Comment?', it: 'Come?', en: 'How?' },
  Liefern: { fr: 'Livraison', it: 'Consegna', en: 'Delivery' },
  '{fee}, ab {min} · PLZ {zips}': { fr: '{fee}, dès {min} · NPA {zips}', it: '{fee}, da {min} · NPA {zips}', en: '{fee}, from {min} · postcodes {zips}' },
  'Wann?': { fr: 'Quand?', it: 'Quando?', en: 'When?' },
  Uhrzeit: { fr: 'Heure', it: 'Ora', en: 'Time' },
  '{day}, {time} Uhr': { fr: '{day}, {time}', it: '{day}, ore {time}', en: '{day}, {time}' },
  'Wer?': { fr: 'Qui?', it: 'Chi?', en: 'Who?' },
  Lieferadresse: { fr: 'Adresse de livraison', it: 'Indirizzo di consegna', en: 'Delivery address' },
  '(nur beim Liefern)': { fr: '(uniquement pour la livraison)', it: '(solo per la consegna)', en: '(delivery only)' },
  'Strasse und Nr.': { fr: 'Rue et n°', it: 'Via e n.', en: 'Street and number' },
  PLZ: { fr: 'NPA', it: 'NPA', en: 'Postcode' },
  Ort: { fr: 'Localité', it: 'Località', en: 'Town' },
  'z. B. ohne Zwiebeln, 2. Stock links': { fr: 'p. ex. sans oignons, 2e étage à gauche', it: 'p. es. senza cipolle, 2° piano a sinistra', en: 'e.g. no onions, 2nd floor left' },
  Bezahlen: { fr: 'Paiement', it: 'Pagamento', en: 'Payment' },
  'Jetzt online': { fr: 'En ligne maintenant', it: 'Online adesso', en: 'Online now' },
  'TWINT, Karte, Apple Pay, Google Pay': { fr: 'TWINT, carte, Apple Pay, Google Pay', it: 'TWINT, carta, Apple Pay, Google Pay', en: 'TWINT, card, Apple Pay, Google Pay' },
  'Bei der Lieferung': { fr: 'À la livraison', it: 'Alla consegna', en: 'On delivery' },
  'Bei der Abholung': { fr: 'Au retrait', it: 'Al ritiro', en: 'On pickup' },
  'Bar oder TWINT': { fr: 'Espèces ou TWINT', it: 'Contanti o TWINT', en: 'Cash or TWINT' },
  'Verbindlich bestellen': { fr: 'Confirmer la commande', it: 'Conferma l’ordine', en: 'Place order' },
  'Preise inkl. MwSt.': { fr: 'Prix TVA incluse.', it: 'Prezzi IVA inclusa.', en: 'Prices incl. VAT.' },
  'Die Küche nimmt gerade keine Bestellungen an.': { fr: 'La cuisine ne prend pas de commandes pour le moment.', it: 'Al momento la cucina non accetta ordini.', en: 'The kitchen isn’t taking orders right now.' },
  'Die Küche nimmt gerade keine Bestellungen an. Bitte versuch es etwas später.': { fr: 'La cuisine ne prend pas de commandes pour le moment. Veuillez réessayer un peu plus tard.', it: 'Al momento la cucina non accetta ordini. Riprova un po’ più tardi.', en: 'The kitchen isn’t taking orders right now. Please try again a little later.' },
  'Abholen ist gerade nicht möglich.': { fr: 'Le retrait n’est pas possible pour le moment.', it: 'Al momento il ritiro non è possibile.', en: 'Pickup isn’t available right now.' },
  'Liefern ist gerade nicht möglich.': { fr: 'La livraison n’est pas possible pour le moment.', it: 'Al momento la consegna non è possibile.', en: 'Delivery isn’t available right now.' },
  'Der Warenkorb ist leer – oder ein Gericht ist inzwischen ausverkauft.': { fr: 'Le panier est vide – ou un plat est épuisé entre-temps.', it: 'Il carrello è vuoto – oppure nel frattempo un piatto è esaurito.', en: 'The cart is empty – or a dish has sold out in the meantime.' },
  'Diese Zeit ist nicht mehr möglich. Bitte wähle eine andere.': { fr: 'Cet horaire n’est plus disponible. Veuillez en choisir un autre.', it: 'Quest’orario non è più disponibile. Scegline un altro.', en: 'This time is no longer available. Please choose another one.' },
  'Bitte gib eine Telefonnummer an – falls etwas ist, rufen wir an.': { fr: 'Veuillez indiquer un numéro de téléphone – en cas de besoin, nous vous appelons.', it: 'Indica un numero di telefono – se c’è qualcosa, ti chiamiamo.', en: 'Please enter a phone number – we’ll call if anything comes up.' },
  'Bitte gib die Lieferadresse an.': { fr: 'Veuillez indiquer l’adresse de livraison.', it: 'Indica l’indirizzo di consegna.', en: 'Please enter the delivery address.' },
  'Nach {zip} liefern wir leider nicht. Möglich: {zips}. Oder hol die Bestellung ab.': { fr: 'Nous ne livrons malheureusement pas à {zip}. Possible : {zips}. Ou venez chercher votre commande.', it: 'Purtroppo non consegniamo a {zip}. Possibile: {zips}. Oppure passa a ritirare l’ordine.', en: 'Sorry, we don’t deliver to {zip}. Possible: {zips}. Or pick up your order.' },
  'Liefern ab {min} Bestellwert. Es fehlen noch {missing}.': { fr: 'Livraison dès {min} de commande. Il manque encore {missing}.', it: 'Consegna con un ordine minimo di {min}. Mancano ancora {missing}.', en: 'Delivery from a minimum order of {min}. You’re {missing} short.' },
  'Online bezahlen geht gerade nicht. Bitte wähle «vor Ort bezahlen».': { fr: 'Le paiement en ligne n’est pas possible pour le moment. Veuillez choisir le paiement sur place.', it: 'Al momento non è possibile pagare online. Scegli il pagamento sul posto.', en: 'Online payment isn’t available right now. Please choose to pay on site.' },
  'Bitte bezahle online.': { fr: 'Veuillez payer en ligne.', it: 'Paga online.', en: 'Please pay online.' },
  'Die Zahlung konnte nicht gestartet werden: {error}': { fr: 'Le paiement n’a pas pu être lancé : {error}', it: 'Non è stato possibile avviare il pagamento: {error}', en: 'The payment could not be started: {error}' },
  // Food ordering: status page and mails
  Bestellung: { fr: 'Commande', it: 'Ordine', en: 'Order' },
  'Bestellung Nr. {n}': { fr: 'Commande n° {n}', it: 'Ordine n. {n}', en: 'Order no. {n}' },
  'Nr. {n}': { fr: 'N° {n}', it: 'N. {n}', en: 'No. {n}' },
  'Die Zahlung wurde abgebrochen.': { fr: 'Le paiement a été interrompu.', it: 'Il pagamento è stato interrotto.', en: 'The payment was cancelled.' },
  'Nochmals versuchen': { fr: 'Réessayer', it: 'Riprova', en: 'Try again' },
  Lieferung: { fr: 'Livraison', it: 'Consegna', en: 'Delivery' },
  Abholung: { fr: 'Retrait', it: 'Ritiro', en: 'Pickup' },
  Bestellt: { fr: 'Commandé', it: 'Ordinato', en: 'Ordered' },
  Total: { fr: 'Total', it: 'Totale', en: 'Total' },
  bezahlt: { fr: 'payé', it: 'pagato', en: 'paid' },
  'Zahlung offen': { fr: 'Paiement en attente', it: 'Pagamento in sospeso', en: 'Payment pending' },
  'bezahlen vor Ort': { fr: 'paiement sur place', it: 'pagamento sul posto', en: 'pay on site' },
  Neu: { fr: 'Nouvelle', it: 'Nuovo', en: 'New' },
  'In Zubereitung': { fr: 'En préparation', it: 'In preparazione', en: 'Being prepared' },
  Bereit: { fr: 'Prête', it: 'Pronto', en: 'Ready' },
  Unterwegs: { fr: 'En route', it: 'In consegna', en: 'On the way' },
  Abgeschlossen: { fr: 'Terminée', it: 'Completato', en: 'Completed' },
  'Wir warten noch auf die Zahlung.': { fr: 'Nous attendons encore le paiement.', it: 'Stiamo ancora aspettando il pagamento.', en: 'We’re still waiting for the payment.' },
  'Deine Bestellung ist angekommen.': { fr: 'Votre commande nous est bien parvenue.', it: 'Abbiamo ricevuto il tuo ordine.', en: 'We’ve received your order.' },
  'Die Küche ist dran.': { fr: 'La cuisine s’en occupe.', it: 'La cucina ci sta lavorando.', en: 'The kitchen is on it.' },
  'Fertig – du kannst sie abholen.': { fr: 'Prête – vous pouvez venir la chercher.', it: 'Pronto – puoi passare a ritirarlo.', en: 'Ready – you can pick it up.' },
  'Ist unterwegs zu dir.': { fr: 'Elle est en route vers vous.', it: 'È in viaggio verso di te.', en: 'On its way to you.' },
  'Erledigt. En Guete!': { fr: 'Terminé. Bon appétit!', it: 'Fatto. Buon appetito!', en: 'All done. Enjoy your meal!' },
  'Diese Bestellung wurde storniert.': { fr: 'Cette commande a été annulée.', it: 'Questo ordine è stato annullato.', en: 'This order has been cancelled.' },
  'danke für deine Bestellung Nr. {n}! Wir liefern {when}.': { fr: 'Merci pour votre commande n° {n}! Livraison prévue : {when}.', it: 'Grazie per il tuo ordine n. {n}! Consegna prevista: {when}.', en: 'Thank you for your order no. {n}! Delivery: {when}.' },
  'danke für deine Bestellung Nr. {n}! Abholbereit {when}.': { fr: 'Merci pour votre commande n° {n}! Prête à emporter : {when}.', it: 'Grazie per il tuo ordine n. {n}! Pronto per il ritiro: {when}.', en: 'Thank you for your order no. {n}! Ready for pickup: {when}.' },
  'deine Bestellung Nr. {n} ist bereit. Bis gleich!': { fr: 'Votre commande n° {n} est prête. À tout de suite!', it: 'Il tuo ordine n. {n} è pronto. A tra poco!', en: 'Your order no. {n} is ready. See you soon!' },
  'deine Bestellung Nr. {n} ist unterwegs zu dir.': { fr: 'Votre commande n° {n} est en route vers vous.', it: 'Il tuo ordine n. {n} è in viaggio verso di te.', en: 'Your order no. {n} is on its way to you.' },
  'deine Bestellung Nr. {n} wurde storniert.': { fr: 'Votre commande n° {n} a été annulée.', it: 'Il tuo ordine n. {n} è stato annullato.', en: 'Your order no. {n} has been cancelled.' },
  'Den Betrag erstatten wir auf dem gleichen Weg zurück.': { fr: 'Nous vous rembourserons le montant par le même moyen de paiement.', it: 'Ti rimborseremo l’importo con lo stesso metodo di pagamento.', en: 'We’ll refund the amount the same way you paid.' },
  'Bestellung Nr. {n} bei {name}': { fr: 'Commande n° {n} chez {name}', it: 'Ordine n. {n} da {name}', en: 'Order no. {n} at {name}' },
  'Bereit zum Abholen: Nr. {n}': { fr: 'Prête à emporter : n° {n}', it: 'Pronto per il ritiro: n. {n}', en: 'Ready for pickup: no. {n}' },
  'Unterwegs: Nr. {n}': { fr: 'En route : n° {n}', it: 'In consegna: n. {n}', en: 'On the way: no. {n}' },
  'Storniert: Nr. {n}': { fr: 'Annulée : n° {n}', it: 'Annullato: n. {n}', en: 'Cancelled: no. {n}' },
  'bezahlen bei Lieferung': { fr: 'paiement à la livraison', it: 'pagamento alla consegna', en: 'pay on delivery' },
  'bezahlen bei Abholung': { fr: 'paiement au retrait', it: 'pagamento al ritiro', en: 'pay on pickup' },
  'Abholen: {place}': { fr: 'Retrait : {place}', it: 'Ritiro: {place}', en: 'Pickup: {place}' },
  'Status ansehen: {link}': { fr: 'Voir le statut : {link}', it: 'Vedi lo stato: {link}', en: 'View status: {link}' },
  // Reservations and appointments
  Reservation: { fr: 'Réservation', it: 'Prenotazione', en: 'Reservation' },
  Termin: { fr: 'Rendez-vous', it: 'Appuntamento', en: 'Appointment' },
  'Deine Reservation': { fr: 'Votre réservation', it: 'La tua prenotazione', en: 'Your reservation' },
  '{n} Person': { fr: '{n} personne', it: '{n} persona', en: '{n} person' },
  '{n} Personen': { fr: '{n} personnes', it: '{n} persone', en: '{n} people' },
  'für {n} Person': { fr: 'pour {n} personne', it: 'per {n} persona', en: 'for {n} person' },
  'für {n} Personen': { fr: 'pour {n} personnes', it: 'per {n} persone', en: 'for {n} people' },
  'Danke! Deine Anfrage ist da. Wir bestätigen sie so bald wie möglich per E-Mail.': { fr: 'Merci! Votre demande nous est parvenue. Nous la confirmerons dès que possible par e-mail.', it: 'Grazie! Abbiamo ricevuto la tua richiesta. Te la confermeremo al più presto per e-mail.', en: 'Thank you! We’ve received your request. We’ll confirm it by email as soon as possible.' },
  'Danke! Deine Reservation ist bestätigt. Die Bestätigung kommt auch per E-Mail.': { fr: 'Merci! Votre réservation est confirmée. Vous recevrez aussi la confirmation par e-mail.', it: 'Grazie! La tua prenotazione è confermata. Riceverai la conferma anche per e-mail.', en: 'Thank you! Your reservation is confirmed. You’ll also get the confirmation by email.' },
  'Danke für die Anzahlung. Deine Reservation ist gesichert.': { fr: 'Merci pour l’acompte. Votre réservation est garantie.', it: 'Grazie per l’acconto. La tua prenotazione è garantita.', en: 'Thank you for the deposit. Your reservation is secured.' },
  'Deine Reservation ist abgesagt. Schade – vielleicht ein anderes Mal.': { fr: 'Votre réservation est annulée. Dommage – peut-être une autre fois.', it: 'La tua prenotazione è annullata. Peccato – magari un’altra volta.', en: 'Your reservation has been cancelled. What a pity – maybe another time.' },
  'Die Zahlung wurde abgebrochen. Ohne Anzahlung wird die Zeit nach 30 Minuten wieder freigegeben.': { fr: 'Le paiement a été interrompu. Sans acompte, le créneau sera libéré après 30 minutes.', it: 'Il pagamento è stato interrotto. Senza acconto, l’orario tornerà libero dopo 30 minuti.', en: 'The payment was cancelled. Without a deposit, the time slot will be released after 30 minutes.' },
  Was: { fr: 'Quoi', it: 'Cosa', en: 'What' },
  Status: { fr: 'Statut', it: 'Stato', en: 'Status' },
  Offen: { fr: 'En attente', it: 'In sospeso', en: 'Pending' },
  'Wartet auf Anzahlung': { fr: 'En attente de l’acompte', it: 'In attesa dell’acconto', en: 'Awaiting deposit' },
  Bestätigt: { fr: 'Confirmée', it: 'Confermata', en: 'Confirmed' },
  Erledigt: { fr: 'Terminée', it: 'Conclusa', en: 'Completed' },
  'Nicht erschienen': { fr: 'Absent', it: 'Assente', en: 'No-show' },
  Storniert: { fr: 'Annulée', it: 'Annullata', en: 'Cancelled' },
  'Anzahlung {amount} bezahlen': { fr: 'Payer l’acompte de {amount}', it: 'Paga l’acconto di {amount}', en: 'Pay deposit of {amount}' },
  'In den Kalender eintragen': { fr: 'Ajouter au calendrier', it: 'Aggiungi al calendario', en: 'Add to calendar' },
  Absagen: { fr: 'Annuler', it: 'Annulla', en: 'Cancel' },
  'Wirklich absagen? Die Zeit wird dann für andere frei.': { fr: 'Vraiment annuler? Le créneau sera alors libéré pour d’autres.', it: 'Vuoi davvero annullare? L’orario tornerà disponibile per altri.', en: 'Really cancel? The time will then be free for others.' },
  'Ja, absagen': { fr: 'Oui, annuler', it: 'Sì, annulla', en: 'Yes, cancel' },
  'Nein, behalten': { fr: 'Non, la garder', it: 'No, la tengo', en: 'No, keep it' },
  'Bitte gib eine gültige E-Mail-Adresse an, damit wir dir die Bestätigung schicken können.': { fr: 'Veuillez indiquer une adresse e-mail valide afin que nous puissions vous envoyer la confirmation.', it: 'Indica un indirizzo e-mail valido, così possiamo inviarti la conferma.', en: 'Please enter a valid email address so we can send you the confirmation.' },
  'Dieses Angebot kann gerade nicht gebucht werden.': { fr: 'Cette offre ne peut pas être réservée pour le moment.', it: 'Al momento questa offerta non è prenotabile.', en: 'This service can’t be booked right now.' },
  'Diese Zeit ist leider gerade vergeben worden. Bitte wähle eine andere.': { fr: 'Cet horaire vient malheureusement d’être réservé. Veuillez en choisir un autre.', it: 'Purtroppo quest’orario è appena stato prenotato. Scegline un altro.', en: 'Sorry, this time has just been taken. Please choose another one.' },
  'Diese Reservation ist nicht mehr aktiv.': { fr: 'Cette réservation n’est plus active.', it: 'Questa prenotazione non è più attiva.', en: 'This reservation is no longer active.' },
  'So kurzfristig geht das nur noch telefonisch.': { fr: 'À si court terme, ce n’est possible que par téléphone.', it: 'Con così poco preavviso è possibile solo per telefono.', en: 'At such short notice, this is only possible by phone.' },
  'So kurzfristig geht das nur noch telefonisch: {phone}.': { fr: 'À si court terme, ce n’est possible que par téléphone : {phone}.', it: 'Con così poco preavviso è possibile solo per telefono: {phone}.', en: 'At such short notice, this is only possible by phone: {phone}.' },
  'Ansehen oder absagen: {link}': { fr: 'Voir ou annuler : {link}', it: 'Vedi o annulla: {link}', en: 'View or cancel: {link}' },
  'Deine Anfrage bei {name}': { fr: 'Votre demande chez {name}', it: 'La tua richiesta da {name}', en: 'Your request at {name}' },
  'Bestätigt: {when}': { fr: 'Confirmée : {when}', it: 'Confermata: {when}', en: 'Confirmed: {when}' },
  'Abgesagt: {when}': { fr: 'Annulée : {when}', it: 'Annullata: {when}', en: 'Cancelled: {when}' },
  'Bis bald: {when}': { fr: 'À bientôt : {when}', it: 'A presto: {when}', en: 'See you soon: {when}' },
  'danke für deine Anfrage {what} am {when}. Wir melden uns, sobald wir sie bestätigt haben.': { fr: 'Merci de votre demande {what} le {when}. Nous vous recontacterons dès que nous l’aurons confirmée.', it: 'Grazie per la tua richiesta {what} – {when}. Ti ricontatteremo non appena l’avremo confermata.', en: 'Thank you for your request {what} on {when}. We’ll be in touch as soon as we’ve confirmed it.' },
  'wir freuen uns auf dich: {when}, {what}.': { fr: 'Nous nous réjouissons de votre visite : {when}, {what}.', it: 'Ti aspettiamo con piacere: {when}, {what}.', en: 'We look forward to seeing you: {when}, {what}.' },
  'deine Reservation am {when} ist abgesagt.': { fr: 'Votre réservation du {when} est annulée.', it: 'La tua prenotazione per {when} è stata annullata.', en: 'Your reservation on {when} has been cancelled.' },
  'zur Erinnerung: {when}, {what}.': { fr: 'Petit rappel : {when}, {what}.', it: 'Promemoria: {when}, {what}.', en: 'A quick reminder: {when}, {what}.' },
  'Anzahlung {what} – {when}': { fr: 'Acompte {what} – {when}', it: 'Acconto {what} – {when}', en: 'Deposit {what} – {when}' },
  'Die Anzahlung konnte nicht gestartet werden: {error}': { fr: 'Le paiement de l’acompte n’a pas pu être lancé : {error}', it: 'Non è stato possibile avviare il pagamento dell’acconto: {error}', en: 'The deposit payment could not be started: {error}' },
};
