import type { CollectionDef } from './types';
import type { FieldDef } from './fields';
import { ACCESS_OPTIONS } from './members';

export const ALLERGENS: { value: string; label: string; short: string }[] = [
  { value: 'gluten', label: 'Glutenhaltiges Getreide', short: 'Gluten' },
  { value: 'crustaceans', label: 'Krebstiere', short: 'Krebstiere' },
  { value: 'eggs', label: 'Eier', short: 'Ei' },
  { value: 'fish', label: 'Fisch', short: 'Fisch' },
  { value: 'peanuts', label: 'Erdnüsse', short: 'Erdnuss' },
  { value: 'soy', label: 'Soja', short: 'Soja' },
  { value: 'milk', label: 'Milch (inkl. Laktose)', short: 'Milch' },
  { value: 'nuts', label: 'Schalenfrüchte (Nüsse)', short: 'Nüsse' },
  { value: 'celery', label: 'Sellerie', short: 'Sellerie' },
  { value: 'mustard', label: 'Senf', short: 'Senf' },
  { value: 'sesame', label: 'Sesam', short: 'Sesam' },
  { value: 'sulphites', label: 'Schwefeldioxid & Sulfite', short: 'Sulfite' },
  { value: 'lupin', label: 'Lupinen', short: 'Lupinen' },
  { value: 'molluscs', label: 'Weichtiere', short: 'Weichtiere' },
];

export const DISH_TAGS = [
  { value: 'vegetarian', label: 'Vegetarisch' },
  { value: 'vegan', label: 'Vegan' },
  { value: 'spicy', label: 'Scharf' },
  { value: 'house', label: 'Hausspezialität' },
];

const seoNote = 'Wird automatisch aus dem Inhalt erzeugt, wenn leer.';

export const PROPERTY_OFFERS = [
  { value: 'rent', label: 'Miete' },
  { value: 'buy', label: 'Kauf' },
];
export const PROPERTY_KINDS = [
  { value: 'apartment', label: 'Wohnung' },
  { value: 'house', label: 'Haus' },
  { value: 'room', label: 'Zimmer / WG' },
  { value: 'commercial', label: 'Büro & Gewerbe' },
  { value: 'parking', label: 'Parkplatz / Garage' },
  { value: 'land', label: 'Grundstück' },
];
export const PROPERTY_STATUS = [
  { value: 'available', label: 'Verfügbar' },
  { value: 'reserved', label: 'Reserviert' },
  { value: 'done', label: 'Vermietet / verkauft' },
];
export const PROPERTY_FEATURES = [
  { value: 'balcony', label: 'Balkon / Terrasse' },
  { value: 'garden', label: 'Garten / Sitzplatz' },
  { value: 'lift', label: 'Lift' },
  { value: 'parking', label: 'Parkplatz / Garage' },
  { value: 'washer', label: 'Eigene Waschmaschine' },
  { value: 'pets', label: 'Haustiere erlaubt' },
  { value: 'accessible', label: 'Rollstuhlgängig' },
  { value: 'minergie', label: 'Minergie' },
  { value: 'view', label: 'Aussicht' },
  { value: 'furnished', label: 'Möbliert' },
  { value: 'fireplace', label: 'Cheminée' },
  { value: 'new', label: 'Neubau / Erstbezug' },
];

function ticketsField(label: string, itemLabel: string, help: string): FieldDef {
  return {
    key: 'tickets',
    type: 'group',
    label,
    itemLabel,
    help,
    fields: [
      { key: 'name', type: 'text', label: 'Bezeichnung', required: true, placeholder: 'z. B. Erwachsene' },
      { key: 'price', type: 'money', label: 'Preis', min: 0 },
      { key: 'capacity', type: 'number', label: 'Plätze', min: 0 },
      { key: 'note', type: 'text', label: 'Hinweis', placeholder: 'z. B. mit Ausweis' },
    ],
  };
}

const accessField: FieldDef = {
  key: 'access',
  type: 'select',
  label: 'Wer darf das sehen?',
  help: 'Mit dem Modul «Mitglieder». Alle anderen sehen Titel, Kurzfassung und eine Einladung, sich anzumelden.',
  options: ACCESS_OPTIONS,
  default: 'public',
  width: 'half',
};

export const BUILTIN_COLLECTIONS: CollectionDef[] = [
  {
    id: 'pages',
    name: 'Seiten',
    singular: 'Seite',
    icon: 'page',
    fields: [{ key: 'title', type: 'text', label: 'Titel der Seite', required: true, maxLength: 120 }, accessField],
    route: '/:slug',
    list_route: null,
    has_blocks: true,
    builtin: true,
    module: null,
    title_field: 'title',
    empty_hint: 'Leg deine erste Seite an – zum Beispiel «Über uns».',
  },
  {
    id: 'posts',
    name: 'Beiträge',
    singular: 'Beitrag',
    icon: 'posts',
    fields: [
      { key: 'title', type: 'text', label: 'Titel', required: true, maxLength: 120 },
      { key: 'excerpt', type: 'textarea', label: 'Kurzfassung', help: 'Erscheint in Übersichten und bei Google. ' + seoNote, maxLength: 300 },
      { key: 'cover', type: 'image', label: 'Titelbild' },
      { key: 'date', type: 'date', label: 'Datum' },
      { key: 'category', type: 'text', label: 'Kategorie', width: 'half' },
      { key: 'tags', type: 'tags', label: 'Schlagwörter', width: 'half' },
      { key: 'series', type: 'text', label: 'Serie', help: 'Beiträge mit gleichem Seriennamen werden miteinander verlinkt.', pro: false },
      { key: 'allowComments', type: 'boolean', label: 'Kommentare erlauben', default: true },
      accessField,
    ],
    route: '/journal/:slug',
    list_route: '/journal',
    has_blocks: true,
    builtin: true,
    module: 'blog',
    title_field: 'title',
    empty_hint: 'Schreib deinen ersten Beitrag. Ein Absatz reicht für den Anfang.',
    sort: { field: 'date', dir: 'desc' },
    per_page: 10,
  },
  {
    id: 'products',
    name: 'Produkte',
    singular: 'Produkt',
    icon: 'bag',
    fields: [
      { key: 'title', type: 'text', label: 'Name', required: true, maxLength: 120 },
      { key: 'price', type: 'money', label: 'Preis (inkl. MwSt.)', required: true, min: 0, width: 'half' },
      { key: 'comparePrice', type: 'money', label: 'Statt-Preis', help: 'Wird durchgestrichen angezeigt.', min: 0, width: 'half' },
      { key: 'images', type: 'images', label: 'Fotos' },
      { key: 'description', type: 'richtext', label: 'Beschreibung' },
      { key: 'category', type: 'text', label: 'Kategorie', width: 'half' },
      { key: 'sku', type: 'text', label: 'Artikelnummer', width: 'half', proLabel: 'sku' },
      { key: 'stock', type: 'number', label: 'An Lager', help: 'Leer lassen, wenn unbegrenzt.', min: 0, width: 'half' },
      {
        key: 'vat',
        type: 'select',
        label: 'Mehrwertsteuer',
        options: [
          { value: 'standard', label: 'Normalsatz' },
          { value: 'reduced', label: 'Reduzierter Satz (Lebensmittel, Bücher)' },
          { value: 'none', label: 'Keine' },
        ],
        default: 'standard',
        width: 'half',
      },
      {
        key: 'variants',
        type: 'group',
        label: 'Varianten',
        itemLabel: 'Variante',
        help: 'Zum Beispiel Grössen oder Farben. Jede Variante hat eigenen Preis und Lagerbestand.',
        fields: [
          { key: 'name', type: 'text', label: 'Name', required: true },
          { key: 'price', type: 'money', label: 'Preis', help: 'Leer = Produktpreis' },
          { key: 'stock', type: 'number', label: 'An Lager', min: 0 },
          { key: 'sku', type: 'text', label: 'Artikelnummer' },
        ],
      },
      { key: 'digital', type: 'boolean', label: 'Digitales Produkt', help: 'Kein Versand. Die Datei wird nach der Zahlung zum Download angeboten.' },
      { key: 'file', type: 'file', label: 'Datei zum Download', private: true, showIf: { field: 'digital', equals: [true] } },
      { key: 'weight', type: 'number', label: 'Gewicht in Gramm', min: 0, pro: true },
    ],
    route: '/laden/:slug',
    list_route: '/laden',
    has_blocks: false,
    builtin: true,
    module: 'shop',
    title_field: 'title',
    empty_hint: 'Leg dein erstes Produkt an: Name, Preis, ein Foto – fertig.',
    sort: { field: 'sort', dir: 'asc' },
    per_page: 24,
  },
  {
    id: 'dishes',
    name: 'Gerichte',
    singular: 'Gericht',
    icon: 'menu',
    fields: [
      { key: 'title', type: 'text', label: 'Name des Gerichts', required: true, maxLength: 120 },
      { key: 'description', type: 'textarea', label: 'Beschreibung', maxLength: 300 },
      { key: 'category', type: 'text', label: 'Kategorie', required: true, help: 'z. B. Vorspeisen, Hauptgang, Dessert, Getränke' },
      {
        key: 'prices',
        type: 'group',
        label: 'Preise',
        itemLabel: 'Preis',
        help: 'Ein Preis genügt. Mehrere für Grössen: «klein / gross», «1 dl / 5 dl».',
        min: 1,
        fields: [
          { key: 'label', type: 'text', label: 'Grösse', help: 'Leer, wenn es nur einen Preis gibt.' },
          { key: 'price', type: 'money', label: 'Preis', required: true },
        ],
      },
      { key: 'allergens', type: 'multiselect', label: 'Allergene', options: ALLERGENS.map(({ value, label }) => ({ value, label })) },
      { key: 'origin', type: 'text', label: 'Herkunft Fleisch/Fisch', help: 'In der Schweiz Pflicht: z. B. «Rind: Schweiz»' },
      { key: 'tags', type: 'multiselect', label: 'Kennzeichnung', options: DISH_TAGS },
      { key: 'daily', type: 'boolean', label: 'Auf der Tageskarte' },
      { key: 'soldOut', type: 'boolean', label: 'Heute ausverkauft' },
    ],
    route: null,
    list_route: '/karte',
    has_blocks: false,
    builtin: true,
    module: 'menu',
    title_field: 'title',
    empty_hint: 'Füg dein erstes Gericht hinzu. Wir haben ein Beispiel vorbereitet, das du übernehmen kannst.',
    sort: { field: 'sort', dir: 'asc' },
  },
  {
    id: 'projects',
    name: 'Projekte',
    singular: 'Projekt',
    icon: 'grid',
    fields: [
      { key: 'title', type: 'text', label: 'Titel', required: true, maxLength: 120 },
      { key: 'client', type: 'text', label: 'Kunde', width: 'half' },
      { key: 'year', type: 'number', label: 'Jahr', width: 'half', min: 1900, max: 2100 },
      { key: 'category', type: 'text', label: 'Kategorie' },
      { key: 'summary', type: 'textarea', label: 'In einem Satz', maxLength: 240 },
      { key: 'cover', type: 'image', label: 'Titelbild', required: true },
      { key: 'images', type: 'images', label: 'Weitere Bilder' },
    ],
    route: '/arbeiten/:slug',
    list_route: '/arbeiten',
    has_blocks: true,
    builtin: true,
    module: 'portfolio',
    title_field: 'title',
    empty_hint: 'Zeig dein erstes Projekt. Ein Titelbild und ein Satz genügen.',
    sort: { field: 'year', dir: 'desc' },
  },
  {
    id: 'profiles',
    name: 'Profile',
    singular: 'Profil',
    icon: 'people',
    fields: [
      { key: 'title', type: 'text', label: 'Name', required: true },
      { key: 'intro', type: 'textarea', label: 'Kurzvorstellung', maxLength: 400 },
      { key: 'images', type: 'images', label: 'Fotos' },
      { key: 'languages', type: 'tags', label: 'Sprachen' },
      { key: 'services', type: 'tags', label: 'Leistungen' },
      {
        key: 'availability',
        type: 'multiselect',
        label: 'Anwesend an',
        options: [
          { value: '1', label: 'Montag' },
          { value: '2', label: 'Dienstag' },
          { value: '3', label: 'Mittwoch' },
          { value: '4', label: 'Donnerstag' },
          { value: '5', label: 'Freitag' },
          { value: '6', label: 'Samstag' },
          { value: '7', label: 'Sonntag' },
        ],
      },
      { key: 'availableNow', type: 'boolean', label: 'Gerade verfügbar' },
      {
        key: 'consentAdult',
        type: 'boolean',
        label: 'Volljährigkeit geprüft',
        help: 'Ausweis wurde gesehen. Ohne diese Bestätigung kann das Profil nicht veröffentlicht werden.',
      },
      {
        key: 'consentPublish',
        type: 'boolean',
        label: 'Einwilligung zur Veröffentlichung liegt vor',
        help: 'Schriftliche Einwilligung der Person zu Text und Bildern.',
      },
      { key: 'consentDate', type: 'date', label: 'Datum der Einwilligung' },
      { key: 'consentDocument', type: 'file', label: 'Einwilligung (Dokument)', private: true, help: 'Wird nie öffentlich angezeigt.' },
    ],
    route: '/profile/:slug',
    list_route: '/profile',
    has_blocks: false,
    builtin: true,
    module: 'profiles',
    title_field: 'title',
    empty_hint: 'Leg das erste Profil an. Es geht erst online, wenn Volljährigkeit und Einwilligung bestätigt sind.',
    sort: { field: 'sort', dir: 'asc' },
  },
  {
    id: 'events',
    name: 'Events',
    singular: 'Event',
    icon: 'ticket',
    fields: [
      { key: 'title', type: 'text', label: 'Titel', required: true, maxLength: 120 },
      { key: 'excerpt', type: 'textarea', label: 'Kurzbeschreibung', help: 'Erscheint in der Übersicht und bei Google. ' + seoNote, maxLength: 300 },
      { key: 'cover', type: 'image', label: 'Bild' },
      { key: 'start', type: 'datetime', label: 'Beginn', required: true, width: 'half' },
      { key: 'end', type: 'datetime', label: 'Ende', width: 'half' },
      { key: 'venue', type: 'text', label: 'Ort', help: 'z. B. «Saal im Rössli». Leer = bei dir.', width: 'half' },
      { key: 'address', type: 'text', label: 'Adresse', help: 'Leer = deine Adresse aus den Einstellungen.', width: 'half' },
      { key: 'category', type: 'text', label: 'Kategorie', width: 'half' },
      { key: 'cancelled', type: 'boolean', label: 'Abgesagt', help: 'Bleibt sichtbar, mit Hinweis. Wer Tickets hat, informierst du am besten per E-Mail.' },
      ticketsField('Tickets', 'Ticketkategorie', 'Leer lassen, wenn es keine Anmeldung braucht. Preis leer = gratis, Plätze leer = unbegrenzt.'),
      { key: 'waitlist', type: 'boolean', label: 'Warteliste, wenn ausverkauft', default: true },
    ],
    route: '/events/:slug',
    list_route: '/events',
    has_blocks: true,
    builtin: true,
    module: 'events',
    title_field: 'title',
    empty_hint: 'Leg dein erstes Event an: Titel, Datum, und wenn nötig Tickets.',
    sort: { field: 'start', dir: 'asc' },
    per_page: 24,
  },
  {
    id: 'courses',
    name: 'Kurse',
    singular: 'Kurs',
    icon: 'calendar',
    fields: [
      { key: 'title', type: 'text', label: 'Titel', required: true, maxLength: 120 },
      { key: 'excerpt', type: 'textarea', label: 'Kurzbeschreibung', help: 'Erscheint in der Übersicht und bei Google. ' + seoNote, maxLength: 300 },
      { key: 'cover', type: 'image', label: 'Bild' },
      {
        key: 'sessions',
        type: 'group',
        label: 'Termine',
        itemLabel: 'Termin',
        min: 1,
        help: 'Alle Daten des Kurses. Die Anmeldung gilt für alle zusammen.',
        fields: [
          { key: 'start', type: 'datetime', label: 'Beginn', required: true },
          { key: 'end', type: 'datetime', label: 'Ende' },
        ],
      },
      {
        key: 'level',
        type: 'select',
        label: 'Niveau',
        options: [
          { value: '', label: 'Keine Angabe' },
          { value: 'Einsteiger', label: 'Einsteiger' },
          { value: 'Mittel', label: 'Mittel' },
          { value: 'Fortgeschrittene', label: 'Fortgeschrittene' },
          { value: 'Alle Niveaus', label: 'Alle Niveaus' },
        ],
        width: 'half',
      },
      { key: 'instructor', type: 'text', label: 'Kursleitung', width: 'half' },
      { key: 'venue', type: 'text', label: 'Ort', width: 'half' },
      { key: 'address', type: 'text', label: 'Adresse', help: 'Leer = deine Adresse aus den Einstellungen.', width: 'half' },
      { key: 'category', type: 'text', label: 'Kategorie', width: 'half' },
      { key: 'cancelled', type: 'boolean', label: 'Abgesagt' },
      ticketsField('Preise & Plätze', 'Preis', 'Meist genügt eine Zeile, z. B. «Teilnahme», CHF 240, 12 Plätze. Für Ermässigungen weitere Zeilen.'),
      { key: 'waitlist', type: 'boolean', label: 'Warteliste, wenn ausgebucht', default: true },
    ],
    route: '/kurse/:slug',
    list_route: '/kurse',
    has_blocks: true,
    builtin: true,
    module: 'courses',
    title_field: 'title',
    empty_hint: 'Leg deinen ersten Kurs an: Termine, Preis und Anzahl Plätze.',
    sort: { field: 'start', dir: 'asc' },
    per_page: 24,
  },
  {
    id: 'properties',
    name: 'Immobilien',
    singular: 'Objekt',
    icon: 'home',
    fields: [
      { key: 'title', type: 'text', label: 'Titel', required: true, maxLength: 120, placeholder: 'z. B. Helle 3½-Zimmer-Wohnung mit Seesicht' },
      { key: 'excerpt', type: 'textarea', label: 'Kurzbeschreibung', help: 'Erscheint in der Liste und bei Google. ' + seoNote, maxLength: 300 },
      { key: 'images', type: 'images', label: 'Fotos', help: 'Das erste Foto ist das Titelbild.' },
      { key: 'offer', type: 'select', label: 'Angebot', options: PROPERTY_OFFERS, default: 'rent', width: 'half', required: true },
      { key: 'kind', type: 'select', label: 'Art', options: PROPERTY_KINDS, default: 'apartment', width: 'half', required: true },
      { key: 'status', type: 'select', label: 'Status', options: PROPERTY_STATUS, default: 'available', width: 'half' },
      { key: 'availableFrom', type: 'text', label: 'Bezug', placeholder: 'ab 1. März oder nach Vereinbarung', width: 'half' },
      { key: 'price', type: 'money', label: 'Preis', help: 'Miete: brutto pro Monat. Kauf: Verkaufspreis. Leer = auf Anfrage.', min: 0, width: 'half' },
      { key: 'extraCosts', type: 'money', label: 'Nebenkosten pro Monat', help: 'Bei Miete: im Bruttopreis enthalten, hier nur zur Info.', min: 0, width: 'half', showIf: { field: 'offer', equals: ['rent'] } },
      { key: 'rooms', type: 'number', label: 'Zimmer', min: 0, max: 50, width: 'half', help: 'z. B. 3.5' },
      { key: 'area', type: 'number', label: 'Wohn-/Nutzfläche in m²', min: 0, width: 'half' },
      { key: 'plot', type: 'number', label: 'Grundstück in m²', min: 0, width: 'half' },
      { key: 'floor', type: 'text', label: 'Etage', placeholder: 'z. B. 2. OG', width: 'half' },
      { key: 'yearBuilt', type: 'number', label: 'Baujahr', min: 1200, max: 2100, width: 'half' },
      { key: 'street', type: 'text', label: 'Strasse', width: 'half' },
      { key: 'zip', type: 'text', label: 'PLZ', width: 'half' },
      { key: 'city', type: 'text', label: 'Ort', required: true, width: 'half' },
      { key: 'showStreet', type: 'boolean', label: 'Strasse öffentlich zeigen', help: 'Aus: nur PLZ und Ort. Die Strasse gibt es auf Anfrage.' },
      { key: 'features', type: 'multiselect', label: 'Ausstattung', options: PROPERTY_FEATURES },
      { key: 'documents', type: 'file', label: 'Dokumentation (PDF)', help: 'Grundriss, Verkaufsdokumentation – zum Herunterladen.' },
    ],
    route: '/immobilien/:slug',
    list_route: '/immobilien',
    has_blocks: true,
    builtin: true,
    module: 'realestate',
    title_field: 'title',
    empty_hint: 'Erfasse dein erstes Objekt: Fotos, Preis, Zimmer, Fläche – fertig.',
    per_page: 24,
  },
  {
    id: 'sections',
    name: 'Sektionen',
    singular: 'Sektion',
    icon: 'link',
    fields: [{ key: 'title', type: 'text', label: 'Name der Sektion', required: true, help: 'Nur intern sichtbar.' }],
    route: null,
    list_route: null,
    has_blocks: true,
    builtin: true,
    module: null,
    title_field: 'title',
    empty_hint: 'Sektionen sind Abschnitte, die du auf mehreren Seiten einsetzt. Ändern an einer Stelle, aktuell überall.',
  },
];

export interface ModuleDef {
  id: string;
  name: string;
  description: string;
  collections: string[];
  status: 'ready' | 'later';
}

export const MODULES: ModuleDef[] = [
  { id: 'blog', name: 'Blog & Magazin', description: 'Beiträge mit Kategorien, Lesezeit, RSS und moderierten Kommentaren.', collections: ['posts'], status: 'ready' },
  { id: 'leads', name: 'Anfragen & Kontakte', description: 'Jede Formular-Anfrage landet als Kontakt mit Status und Notizen.', collections: [], status: 'ready' },
  { id: 'shop', name: 'Shop', description: 'Produkte, Varianten, Lager, Warenkorb, Gutscheine, MwSt. – Bezahlung via Stripe oder Rechnung.', collections: ['products'], status: 'ready' },
  { id: 'menu', name: 'Speisekarte', description: 'Gerichte mit Allergenen, Herkunft, Preisen pro Grösse, Tageskarte, Druckversion und QR-Code.', collections: ['dishes'], status: 'ready' },
  { id: 'portfolio', name: 'Portfolio', description: 'Projekte mit Bildern, Filter und Vergrösserung.', collections: ['projects'], status: 'ready' },
  { id: 'profiles', name: 'Profile & Verfügbarkeit', description: 'Personenprofile mit Anwesenheit – inklusive Einwilligungsnachweis.', collections: ['profiles'], status: 'ready' },
  { id: 'booking', name: 'Reservation & Termine', description: 'Tische oder Termine online buchen: freie Zeiten aus den Öffnungszeiten, Bestätigung und Erinnerung per E-Mail, Kalender-Abo.', collections: [], status: 'ready' },
  { id: 'newsletter', name: 'Newsletter', description: 'Anmeldung mit Bestätigung per E-Mail, neue Beiträge verschicken – von Hand, einzeln oder als Wochenrückblick. Abmelden mit einem Klick.', collections: [], status: 'ready' },
  { id: 'members', name: 'Mitglieder', description: 'Konten für Besucher:innen, Seiten und Beiträge nur für Mitglieder, bezahlte Mitgliedschaft im Abo über Stripe.', collections: [], status: 'ready' },
  { id: 'realestate', name: 'Immobilien', description: 'Objekte zur Miete oder zum Kauf mit Fotos, Eckdaten und Ausstattung, Suche mit Filtern, Anfragen direkt ins CRM.', collections: ['properties'], status: 'ready' },
  { id: 'donations', name: 'Spenden', description: 'Spendenformular mit Beträgen, einmalig oder monatlich über Stripe, Kampagnenziel mit Fortschritt, Spendenbestätigungen fürs Steueramt.', collections: [], status: 'ready' },
  { id: 'events', name: 'Events & Tickets', description: 'Eventkalender, Ticketkategorien mit Kontingent, gratis oder über Stripe, Tickets mit QR-Code und Einlass-Scanner, Warteliste.', collections: ['events'], status: 'ready' },
  { id: 'courses', name: 'Kurse', description: 'Kurse mit mehreren Terminen, Plätzen und Preisen, Anmeldung online, Teilnehmerliste und Warteliste.', collections: ['courses'], status: 'ready' },
];

export interface SectorDef {
  id: string;
  name: string;
  hint: string;
  modules: string[];
  themes: [string, string, string];
  businessType: string;
}

/** Sparten. Each is a combination of modules and a theme recommendation – no own code path. */
export const SECTORS: SectorDef[] = [
  { id: 'restaurant', name: 'Restaurant, Café, Bar', hint: 'Karte, Reservation, Öffnungszeiten', modules: ['menu', 'booking', 'leads'], themes: ['bistro', 'salon', 'kante'], businessType: 'Restaurant' },
  { id: 'shop', name: 'Online-Shop', hint: 'Produkte verkaufen, mit TWINT & Karte', modules: ['shop'], themes: ['kante', 'bistro', 'salon'], businessType: 'Store' },
  { id: 'blog', name: 'Blog oder Magazin', hint: 'Schreiben, gefunden werden', modules: ['blog', 'newsletter'], themes: ['feuilleton', 'kante', 'bistro'], businessType: 'Organization' },
  { id: 'landing', name: 'Angebot mit Anfragen', hint: 'Eine Seite, die Anfragen sammelt', modules: ['leads'], themes: ['kante', 'feuilleton', 'salon'], businessType: 'ProfessionalService' },
  { id: 'trade', name: 'Handwerk & KMU', hint: 'Leistungen, Referenzen, Offerten', modules: ['leads', 'portfolio'], themes: ['kante', 'bistro', 'feuilleton'], businessType: 'HomeAndConstructionBusiness' },
  { id: 'studio', name: 'Coiffeur, Kosmetik, Studio', hint: 'Preisliste, Team, Termine online', modules: ['booking', 'leads'], themes: ['salon', 'bistro', 'kante'], businessType: 'BeautySalon' },
  { id: 'practice', name: 'Praxis & Therapie', hint: 'Angebot, Termine online, Anfahrt', modules: ['booking', 'leads', 'courses'], themes: ['feuilleton', 'kante', 'bistro'], businessType: 'MedicalBusiness' },
  { id: 'portfolio', name: 'Portfolio & Agentur', hint: 'Arbeiten zeigen', modules: ['portfolio', 'leads'], themes: ['kante', 'feuilleton', 'salon'], businessType: 'ProfessionalService' },
  { id: 'realestate', name: 'Immobilien & Verwaltung', hint: 'Objekte, Suche mit Filtern, Anfragen', modules: ['realestate', 'leads', 'newsletter'], themes: ['kante', 'feuilleton', 'salon'], businessType: 'RealEstateAgent' },
  { id: 'hotel', name: 'Hotel & Ferienwohnung', hint: 'Zimmer, Lage, Anfragen', modules: ['leads'], themes: ['salon', 'bistro', 'feuilleton'], businessType: 'LodgingBusiness' },
  { id: 'club', name: 'Verein', hint: 'Neuigkeiten, Termine, Mitmachen', modules: ['blog', 'leads', 'newsletter', 'members', 'events'], themes: ['kante', 'bistro', 'feuilleton'], businessType: 'SportsOrganization' },
  { id: 'nonprofit', name: 'Non-Profit', hint: 'Anliegen erklären, Unterstützung gewinnen', modules: ['blog', 'leads', 'newsletter', 'donations'], themes: ['feuilleton', 'kante', 'bistro'], businessType: 'NGO' },
  { id: 'adult', name: 'Erotikbetrieb', hint: 'Bordell, Studio, Agentur – mit Altersschranke', modules: ['profiles', 'leads'], themes: ['salon', 'kante', 'feuilleton'], businessType: 'LocalBusiness' },
];

export const SECTOR_MAP = Object.fromEntries(SECTORS.map((s) => [s.id, s]));

